# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef FB_BOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
# define FB_BOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
#
# include <firebird/impl/boost/preprocessor/control/iif.hpp>
#
# /* FB_BOOST_PP_AUTO_REC */
#
# define FB_BOOST_PP_AUTO_REC(pred, n) FB_BOOST_PP_NODE_ENTRY_ ## n(pred)
#
# define FB_BOOST_PP_NODE_ENTRY_256(p) FB_BOOST_PP_NODE_128(p)(p)(p)(p)(p)(p)(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_128(p) FB_BOOST_PP_NODE_64(p)(p)(p)(p)(p)(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_64(p) FB_BOOST_PP_NODE_32(p)(p)(p)(p)(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_32(p) FB_BOOST_PP_NODE_16(p)(p)(p)(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_16(p) FB_BOOST_PP_NODE_8(p)(p)(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_8(p) FB_BOOST_PP_NODE_4(p)(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_4(p) FB_BOOST_PP_NODE_2(p)(p)
# define FB_BOOST_PP_NODE_ENTRY_2(p) FB_BOOST_PP_NODE_1(p)
#
# define FB_BOOST_PP_NODE_128(p) FB_BOOST_PP_IIF(p##(128), FB_BOOST_PP_NODE_64, FB_BOOST_PP_NODE_192)
#    define FB_BOOST_PP_NODE_64(p) FB_BOOST_PP_IIF(p##(64), FB_BOOST_PP_NODE_32, FB_BOOST_PP_NODE_96)
#        define FB_BOOST_PP_NODE_32(p) FB_BOOST_PP_IIF(p##(32), FB_BOOST_PP_NODE_16, FB_BOOST_PP_NODE_48)
#            define FB_BOOST_PP_NODE_16(p) FB_BOOST_PP_IIF(p##(16), FB_BOOST_PP_NODE_8, FB_BOOST_PP_NODE_24)
#                define FB_BOOST_PP_NODE_8(p) FB_BOOST_PP_IIF(p##(8), FB_BOOST_PP_NODE_4, FB_BOOST_PP_NODE_12)
#                    define FB_BOOST_PP_NODE_4(p) FB_BOOST_PP_IIF(p##(4), FB_BOOST_PP_NODE_2, FB_BOOST_PP_NODE_6)
#                        define FB_BOOST_PP_NODE_2(p) FB_BOOST_PP_IIF(p##(2), FB_BOOST_PP_NODE_1, FB_BOOST_PP_NODE_3)
#                            define FB_BOOST_PP_NODE_1(p) FB_BOOST_PP_IIF(p##(1), 1, 2)
#                            define FB_BOOST_PP_NODE_3(p) FB_BOOST_PP_IIF(p##(3), 3, 4)
#                        define FB_BOOST_PP_NODE_6(p) FB_BOOST_PP_IIF(p##(6), FB_BOOST_PP_NODE_5, FB_BOOST_PP_NODE_7)
#                            define FB_BOOST_PP_NODE_5(p) FB_BOOST_PP_IIF(p##(5), 5, 6)
#                            define FB_BOOST_PP_NODE_7(p) FB_BOOST_PP_IIF(p##(7), 7, 8)
#                    define FB_BOOST_PP_NODE_12(p) FB_BOOST_PP_IIF(p##(12), FB_BOOST_PP_NODE_10, FB_BOOST_PP_NODE_14)
#                        define FB_BOOST_PP_NODE_10(p) FB_BOOST_PP_IIF(p##(10), FB_BOOST_PP_NODE_9, FB_BOOST_PP_NODE_11)
#                            define FB_BOOST_PP_NODE_9(p) FB_BOOST_PP_IIF(p##(9), 9, 10)
#                            define FB_BOOST_PP_NODE_11(p) FB_BOOST_PP_IIF(p##(11), 11, 12)
#                        define FB_BOOST_PP_NODE_14(p) FB_BOOST_PP_IIF(p##(14), FB_BOOST_PP_NODE_13, FB_BOOST_PP_NODE_15)
#                            define FB_BOOST_PP_NODE_13(p) FB_BOOST_PP_IIF(p##(13), 13, 14)
#                            define FB_BOOST_PP_NODE_15(p) FB_BOOST_PP_IIF(p##(15), 15, 16)
#                define FB_BOOST_PP_NODE_24(p) FB_BOOST_PP_IIF(p##(24), FB_BOOST_PP_NODE_20, FB_BOOST_PP_NODE_28)
#                    define FB_BOOST_PP_NODE_20(p) FB_BOOST_PP_IIF(p##(20), FB_BOOST_PP_NODE_18, FB_BOOST_PP_NODE_22)
#                        define FB_BOOST_PP_NODE_18(p) FB_BOOST_PP_IIF(p##(18), FB_BOOST_PP_NODE_17, FB_BOOST_PP_NODE_19)
#                            define FB_BOOST_PP_NODE_17(p) FB_BOOST_PP_IIF(p##(17), 17, 18)
#                            define FB_BOOST_PP_NODE_19(p) FB_BOOST_PP_IIF(p##(19), 19, 20)
#                        define FB_BOOST_PP_NODE_22(p) FB_BOOST_PP_IIF(p##(22), FB_BOOST_PP_NODE_21, FB_BOOST_PP_NODE_23)
#                            define FB_BOOST_PP_NODE_21(p) FB_BOOST_PP_IIF(p##(21), 21, 22)
#                            define FB_BOOST_PP_NODE_23(p) FB_BOOST_PP_IIF(p##(23), 23, 24)
#                    define FB_BOOST_PP_NODE_28(p) FB_BOOST_PP_IIF(p##(28), FB_BOOST_PP_NODE_26, FB_BOOST_PP_NODE_30)
#                        define FB_BOOST_PP_NODE_26(p) FB_BOOST_PP_IIF(p##(26), FB_BOOST_PP_NODE_25, FB_BOOST_PP_NODE_27)
#                            define FB_BOOST_PP_NODE_25(p) FB_BOOST_PP_IIF(p##(25), 25, 26)
#                            define FB_BOOST_PP_NODE_27(p) FB_BOOST_PP_IIF(p##(27), 27, 28)
#                        define FB_BOOST_PP_NODE_30(p) FB_BOOST_PP_IIF(p##(30), FB_BOOST_PP_NODE_29, FB_BOOST_PP_NODE_31)
#                            define FB_BOOST_PP_NODE_29(p) FB_BOOST_PP_IIF(p##(29), 29, 30)
#                            define FB_BOOST_PP_NODE_31(p) FB_BOOST_PP_IIF(p##(31), 31, 32)
#            define FB_BOOST_PP_NODE_48(p) FB_BOOST_PP_IIF(p##(48), FB_BOOST_PP_NODE_40, FB_BOOST_PP_NODE_56)
#                define FB_BOOST_PP_NODE_40(p) FB_BOOST_PP_IIF(p##(40), FB_BOOST_PP_NODE_36, FB_BOOST_PP_NODE_44)
#                    define FB_BOOST_PP_NODE_36(p) FB_BOOST_PP_IIF(p##(36), FB_BOOST_PP_NODE_34, FB_BOOST_PP_NODE_38)
#                        define FB_BOOST_PP_NODE_34(p) FB_BOOST_PP_IIF(p##(34), FB_BOOST_PP_NODE_33, FB_BOOST_PP_NODE_35)
#                            define FB_BOOST_PP_NODE_33(p) FB_BOOST_PP_IIF(p##(33), 33, 34)
#                            define FB_BOOST_PP_NODE_35(p) FB_BOOST_PP_IIF(p##(35), 35, 36)
#                        define FB_BOOST_PP_NODE_38(p) FB_BOOST_PP_IIF(p##(38), FB_BOOST_PP_NODE_37, FB_BOOST_PP_NODE_39)
#                            define FB_BOOST_PP_NODE_37(p) FB_BOOST_PP_IIF(p##(37), 37, 38)
#                            define FB_BOOST_PP_NODE_39(p) FB_BOOST_PP_IIF(p##(39), 39, 40)
#                    define FB_BOOST_PP_NODE_44(p) FB_BOOST_PP_IIF(p##(44), FB_BOOST_PP_NODE_42, FB_BOOST_PP_NODE_46)
#                        define FB_BOOST_PP_NODE_42(p) FB_BOOST_PP_IIF(p##(42), FB_BOOST_PP_NODE_41, FB_BOOST_PP_NODE_43)
#                            define FB_BOOST_PP_NODE_41(p) FB_BOOST_PP_IIF(p##(41), 41, 42)
#                            define FB_BOOST_PP_NODE_43(p) FB_BOOST_PP_IIF(p##(43), 43, 44)
#                        define FB_BOOST_PP_NODE_46(p) FB_BOOST_PP_IIF(p##(46), FB_BOOST_PP_NODE_45, FB_BOOST_PP_NODE_47)
#                            define FB_BOOST_PP_NODE_45(p) FB_BOOST_PP_IIF(p##(45), 45, 46)
#                            define FB_BOOST_PP_NODE_47(p) FB_BOOST_PP_IIF(p##(47), 47, 48)
#                define FB_BOOST_PP_NODE_56(p) FB_BOOST_PP_IIF(p##(56), FB_BOOST_PP_NODE_52, FB_BOOST_PP_NODE_60)
#                    define FB_BOOST_PP_NODE_52(p) FB_BOOST_PP_IIF(p##(52), FB_BOOST_PP_NODE_50, FB_BOOST_PP_NODE_54)
#                        define FB_BOOST_PP_NODE_50(p) FB_BOOST_PP_IIF(p##(50), FB_BOOST_PP_NODE_49, FB_BOOST_PP_NODE_51)
#                            define FB_BOOST_PP_NODE_49(p) FB_BOOST_PP_IIF(p##(49), 49, 50)
#                            define FB_BOOST_PP_NODE_51(p) FB_BOOST_PP_IIF(p##(51), 51, 52)
#                        define FB_BOOST_PP_NODE_54(p) FB_BOOST_PP_IIF(p##(54), FB_BOOST_PP_NODE_53, FB_BOOST_PP_NODE_55)
#                            define FB_BOOST_PP_NODE_53(p) FB_BOOST_PP_IIF(p##(53), 53, 54)
#                            define FB_BOOST_PP_NODE_55(p) FB_BOOST_PP_IIF(p##(55), 55, 56)
#                    define FB_BOOST_PP_NODE_60(p) FB_BOOST_PP_IIF(p##(60), FB_BOOST_PP_NODE_58, FB_BOOST_PP_NODE_62)
#                        define FB_BOOST_PP_NODE_58(p) FB_BOOST_PP_IIF(p##(58), FB_BOOST_PP_NODE_57, FB_BOOST_PP_NODE_59)
#                            define FB_BOOST_PP_NODE_57(p) FB_BOOST_PP_IIF(p##(57), 57, 58)
#                            define FB_BOOST_PP_NODE_59(p) FB_BOOST_PP_IIF(p##(59), 59, 60)
#                        define FB_BOOST_PP_NODE_62(p) FB_BOOST_PP_IIF(p##(62), FB_BOOST_PP_NODE_61, FB_BOOST_PP_NODE_63)
#                            define FB_BOOST_PP_NODE_61(p) FB_BOOST_PP_IIF(p##(61), 61, 62)
#                            define FB_BOOST_PP_NODE_63(p) FB_BOOST_PP_IIF(p##(63), 63, 64)
#        define FB_BOOST_PP_NODE_96(p) FB_BOOST_PP_IIF(p##(96), FB_BOOST_PP_NODE_80, FB_BOOST_PP_NODE_112)
#            define FB_BOOST_PP_NODE_80(p) FB_BOOST_PP_IIF(p##(80), FB_BOOST_PP_NODE_72, FB_BOOST_PP_NODE_88)
#                define FB_BOOST_PP_NODE_72(p) FB_BOOST_PP_IIF(p##(72), FB_BOOST_PP_NODE_68, FB_BOOST_PP_NODE_76)
#                    define FB_BOOST_PP_NODE_68(p) FB_BOOST_PP_IIF(p##(68), FB_BOOST_PP_NODE_66, FB_BOOST_PP_NODE_70)
#                        define FB_BOOST_PP_NODE_66(p) FB_BOOST_PP_IIF(p##(66), FB_BOOST_PP_NODE_65, FB_BOOST_PP_NODE_67)
#                            define FB_BOOST_PP_NODE_65(p) FB_BOOST_PP_IIF(p##(65), 65, 66)
#                            define FB_BOOST_PP_NODE_67(p) FB_BOOST_PP_IIF(p##(67), 67, 68)
#                        define FB_BOOST_PP_NODE_70(p) FB_BOOST_PP_IIF(p##(70), FB_BOOST_PP_NODE_69, FB_BOOST_PP_NODE_71)
#                            define FB_BOOST_PP_NODE_69(p) FB_BOOST_PP_IIF(p##(69), 69, 70)
#                            define FB_BOOST_PP_NODE_71(p) FB_BOOST_PP_IIF(p##(71), 71, 72)
#                    define FB_BOOST_PP_NODE_76(p) FB_BOOST_PP_IIF(p##(76), FB_BOOST_PP_NODE_74, FB_BOOST_PP_NODE_78)
#                        define FB_BOOST_PP_NODE_74(p) FB_BOOST_PP_IIF(p##(74), FB_BOOST_PP_NODE_73, FB_BOOST_PP_NODE_75)
#                            define FB_BOOST_PP_NODE_73(p) FB_BOOST_PP_IIF(p##(73), 73, 74)
#                            define FB_BOOST_PP_NODE_75(p) FB_BOOST_PP_IIF(p##(75), 75, 76)
#                        define FB_BOOST_PP_NODE_78(p) FB_BOOST_PP_IIF(p##(78), FB_BOOST_PP_NODE_77, FB_BOOST_PP_NODE_79)
#                            define FB_BOOST_PP_NODE_77(p) FB_BOOST_PP_IIF(p##(77), 77, 78)
#                            define FB_BOOST_PP_NODE_79(p) FB_BOOST_PP_IIF(p##(79), 79, 80)
#                define FB_BOOST_PP_NODE_88(p) FB_BOOST_PP_IIF(p##(88), FB_BOOST_PP_NODE_84, FB_BOOST_PP_NODE_92)
#                    define FB_BOOST_PP_NODE_84(p) FB_BOOST_PP_IIF(p##(84), FB_BOOST_PP_NODE_82, FB_BOOST_PP_NODE_86)
#                        define FB_BOOST_PP_NODE_82(p) FB_BOOST_PP_IIF(p##(82), FB_BOOST_PP_NODE_81, FB_BOOST_PP_NODE_83)
#                            define FB_BOOST_PP_NODE_81(p) FB_BOOST_PP_IIF(p##(81), 81, 82)
#                            define FB_BOOST_PP_NODE_83(p) FB_BOOST_PP_IIF(p##(83), 83, 84)
#                        define FB_BOOST_PP_NODE_86(p) FB_BOOST_PP_IIF(p##(86), FB_BOOST_PP_NODE_85, FB_BOOST_PP_NODE_87)
#                            define FB_BOOST_PP_NODE_85(p) FB_BOOST_PP_IIF(p##(85), 85, 86)
#                            define FB_BOOST_PP_NODE_87(p) FB_BOOST_PP_IIF(p##(87), 87, 88)
#                    define FB_BOOST_PP_NODE_92(p) FB_BOOST_PP_IIF(p##(92), FB_BOOST_PP_NODE_90, FB_BOOST_PP_NODE_94)
#                        define FB_BOOST_PP_NODE_90(p) FB_BOOST_PP_IIF(p##(90), FB_BOOST_PP_NODE_89, FB_BOOST_PP_NODE_91)
#                            define FB_BOOST_PP_NODE_89(p) FB_BOOST_PP_IIF(p##(89), 89, 90)
#                            define FB_BOOST_PP_NODE_91(p) FB_BOOST_PP_IIF(p##(91), 91, 92)
#                        define FB_BOOST_PP_NODE_94(p) FB_BOOST_PP_IIF(p##(94), FB_BOOST_PP_NODE_93, FB_BOOST_PP_NODE_95)
#                            define FB_BOOST_PP_NODE_93(p) FB_BOOST_PP_IIF(p##(93), 93, 94)
#                            define FB_BOOST_PP_NODE_95(p) FB_BOOST_PP_IIF(p##(95), 95, 96)
#            define FB_BOOST_PP_NODE_112(p) FB_BOOST_PP_IIF(p##(112), FB_BOOST_PP_NODE_104, FB_BOOST_PP_NODE_120)
#                define FB_BOOST_PP_NODE_104(p) FB_BOOST_PP_IIF(p##(104), FB_BOOST_PP_NODE_100, FB_BOOST_PP_NODE_108)
#                    define FB_BOOST_PP_NODE_100(p) FB_BOOST_PP_IIF(p##(100), FB_BOOST_PP_NODE_98, FB_BOOST_PP_NODE_102)
#                        define FB_BOOST_PP_NODE_98(p) FB_BOOST_PP_IIF(p##(98), FB_BOOST_PP_NODE_97, FB_BOOST_PP_NODE_99)
#                            define FB_BOOST_PP_NODE_97(p) FB_BOOST_PP_IIF(p##(97), 97, 98)
#                            define FB_BOOST_PP_NODE_99(p) FB_BOOST_PP_IIF(p##(99), 99, 100)
#                        define FB_BOOST_PP_NODE_102(p) FB_BOOST_PP_IIF(p##(102), FB_BOOST_PP_NODE_101, FB_BOOST_PP_NODE_103)
#                            define FB_BOOST_PP_NODE_101(p) FB_BOOST_PP_IIF(p##(101), 101, 102)
#                            define FB_BOOST_PP_NODE_103(p) FB_BOOST_PP_IIF(p##(103), 103, 104)
#                    define FB_BOOST_PP_NODE_108(p) FB_BOOST_PP_IIF(p##(108), FB_BOOST_PP_NODE_106, FB_BOOST_PP_NODE_110)
#                        define FB_BOOST_PP_NODE_106(p) FB_BOOST_PP_IIF(p##(106), FB_BOOST_PP_NODE_105, FB_BOOST_PP_NODE_107)
#                            define FB_BOOST_PP_NODE_105(p) FB_BOOST_PP_IIF(p##(105), 105, 106)
#                            define FB_BOOST_PP_NODE_107(p) FB_BOOST_PP_IIF(p##(107), 107, 108)
#                        define FB_BOOST_PP_NODE_110(p) FB_BOOST_PP_IIF(p##(110), FB_BOOST_PP_NODE_109, FB_BOOST_PP_NODE_111)
#                            define FB_BOOST_PP_NODE_109(p) FB_BOOST_PP_IIF(p##(109), 109, 110)
#                            define FB_BOOST_PP_NODE_111(p) FB_BOOST_PP_IIF(p##(111), 111, 112)
#                define FB_BOOST_PP_NODE_120(p) FB_BOOST_PP_IIF(p##(120), FB_BOOST_PP_NODE_116, FB_BOOST_PP_NODE_124)
#                    define FB_BOOST_PP_NODE_116(p) FB_BOOST_PP_IIF(p##(116), FB_BOOST_PP_NODE_114, FB_BOOST_PP_NODE_118)
#                        define FB_BOOST_PP_NODE_114(p) FB_BOOST_PP_IIF(p##(114), FB_BOOST_PP_NODE_113, FB_BOOST_PP_NODE_115)
#                            define FB_BOOST_PP_NODE_113(p) FB_BOOST_PP_IIF(p##(113), 113, 114)
#                            define FB_BOOST_PP_NODE_115(p) FB_BOOST_PP_IIF(p##(115), 115, 116)
#                        define FB_BOOST_PP_NODE_118(p) FB_BOOST_PP_IIF(p##(118), FB_BOOST_PP_NODE_117, FB_BOOST_PP_NODE_119)
#                            define FB_BOOST_PP_NODE_117(p) FB_BOOST_PP_IIF(p##(117), 117, 118)
#                            define FB_BOOST_PP_NODE_119(p) FB_BOOST_PP_IIF(p##(119), 119, 120)
#                    define FB_BOOST_PP_NODE_124(p) FB_BOOST_PP_IIF(p##(124), FB_BOOST_PP_NODE_122, FB_BOOST_PP_NODE_126)
#                        define FB_BOOST_PP_NODE_122(p) FB_BOOST_PP_IIF(p##(122), FB_BOOST_PP_NODE_121, FB_BOOST_PP_NODE_123)
#                            define FB_BOOST_PP_NODE_121(p) FB_BOOST_PP_IIF(p##(121), 121, 122)
#                            define FB_BOOST_PP_NODE_123(p) FB_BOOST_PP_IIF(p##(123), 123, 124)
#                        define FB_BOOST_PP_NODE_126(p) FB_BOOST_PP_IIF(p##(126), FB_BOOST_PP_NODE_125, FB_BOOST_PP_NODE_127)
#                            define FB_BOOST_PP_NODE_125(p) FB_BOOST_PP_IIF(p##(125), 125, 126)
#                            define FB_BOOST_PP_NODE_127(p) FB_BOOST_PP_IIF(p##(127), 127, 128)
#    define FB_BOOST_PP_NODE_192(p) FB_BOOST_PP_IIF(p##(192), FB_BOOST_PP_NODE_160, FB_BOOST_PP_NODE_224)
#        define FB_BOOST_PP_NODE_160(p) FB_BOOST_PP_IIF(p##(160), FB_BOOST_PP_NODE_144, FB_BOOST_PP_NODE_176)
#            define FB_BOOST_PP_NODE_144(p) FB_BOOST_PP_IIF(p##(144), FB_BOOST_PP_NODE_136, FB_BOOST_PP_NODE_152)
#                define FB_BOOST_PP_NODE_136(p) FB_BOOST_PP_IIF(p##(136), FB_BOOST_PP_NODE_132, FB_BOOST_PP_NODE_140)
#                    define FB_BOOST_PP_NODE_132(p) FB_BOOST_PP_IIF(p##(132), FB_BOOST_PP_NODE_130, FB_BOOST_PP_NODE_134)
#                        define FB_BOOST_PP_NODE_130(p) FB_BOOST_PP_IIF(p##(130), FB_BOOST_PP_NODE_129, FB_BOOST_PP_NODE_131)
#                            define FB_BOOST_PP_NODE_129(p) FB_BOOST_PP_IIF(p##(129), 129, 130)
#                            define FB_BOOST_PP_NODE_131(p) FB_BOOST_PP_IIF(p##(131), 131, 132)
#                        define FB_BOOST_PP_NODE_134(p) FB_BOOST_PP_IIF(p##(134), FB_BOOST_PP_NODE_133, FB_BOOST_PP_NODE_135)
#                            define FB_BOOST_PP_NODE_133(p) FB_BOOST_PP_IIF(p##(133), 133, 134)
#                            define FB_BOOST_PP_NODE_135(p) FB_BOOST_PP_IIF(p##(135), 135, 136)
#                    define FB_BOOST_PP_NODE_140(p) FB_BOOST_PP_IIF(p##(140), FB_BOOST_PP_NODE_138, FB_BOOST_PP_NODE_142)
#                        define FB_BOOST_PP_NODE_138(p) FB_BOOST_PP_IIF(p##(138), FB_BOOST_PP_NODE_137, FB_BOOST_PP_NODE_139)
#                            define FB_BOOST_PP_NODE_137(p) FB_BOOST_PP_IIF(p##(137), 137, 138)
#                            define FB_BOOST_PP_NODE_139(p) FB_BOOST_PP_IIF(p##(139), 139, 140)
#                        define FB_BOOST_PP_NODE_142(p) FB_BOOST_PP_IIF(p##(142), FB_BOOST_PP_NODE_141, FB_BOOST_PP_NODE_143)
#                            define FB_BOOST_PP_NODE_141(p) FB_BOOST_PP_IIF(p##(141), 141, 142)
#                            define FB_BOOST_PP_NODE_143(p) FB_BOOST_PP_IIF(p##(143), 143, 144)
#                define FB_BOOST_PP_NODE_152(p) FB_BOOST_PP_IIF(p##(152), FB_BOOST_PP_NODE_148, FB_BOOST_PP_NODE_156)
#                    define FB_BOOST_PP_NODE_148(p) FB_BOOST_PP_IIF(p##(148), FB_BOOST_PP_NODE_146, FB_BOOST_PP_NODE_150)
#                        define FB_BOOST_PP_NODE_146(p) FB_BOOST_PP_IIF(p##(146), FB_BOOST_PP_NODE_145, FB_BOOST_PP_NODE_147)
#                            define FB_BOOST_PP_NODE_145(p) FB_BOOST_PP_IIF(p##(145), 145, 146)
#                            define FB_BOOST_PP_NODE_147(p) FB_BOOST_PP_IIF(p##(147), 147, 148)
#                        define FB_BOOST_PP_NODE_150(p) FB_BOOST_PP_IIF(p##(150), FB_BOOST_PP_NODE_149, FB_BOOST_PP_NODE_151)
#                            define FB_BOOST_PP_NODE_149(p) FB_BOOST_PP_IIF(p##(149), 149, 150)
#                            define FB_BOOST_PP_NODE_151(p) FB_BOOST_PP_IIF(p##(151), 151, 152)
#                    define FB_BOOST_PP_NODE_156(p) FB_BOOST_PP_IIF(p##(156), FB_BOOST_PP_NODE_154, FB_BOOST_PP_NODE_158)
#                        define FB_BOOST_PP_NODE_154(p) FB_BOOST_PP_IIF(p##(154), FB_BOOST_PP_NODE_153, FB_BOOST_PP_NODE_155)
#                            define FB_BOOST_PP_NODE_153(p) FB_BOOST_PP_IIF(p##(153), 153, 154)
#                            define FB_BOOST_PP_NODE_155(p) FB_BOOST_PP_IIF(p##(155), 155, 156)
#                        define FB_BOOST_PP_NODE_158(p) FB_BOOST_PP_IIF(p##(158), FB_BOOST_PP_NODE_157, FB_BOOST_PP_NODE_159)
#                            define FB_BOOST_PP_NODE_157(p) FB_BOOST_PP_IIF(p##(157), 157, 158)
#                            define FB_BOOST_PP_NODE_159(p) FB_BOOST_PP_IIF(p##(159), 159, 160)
#            define FB_BOOST_PP_NODE_176(p) FB_BOOST_PP_IIF(p##(176), FB_BOOST_PP_NODE_168, FB_BOOST_PP_NODE_184)
#                define FB_BOOST_PP_NODE_168(p) FB_BOOST_PP_IIF(p##(168), FB_BOOST_PP_NODE_164, FB_BOOST_PP_NODE_172)
#                    define FB_BOOST_PP_NODE_164(p) FB_BOOST_PP_IIF(p##(164), FB_BOOST_PP_NODE_162, FB_BOOST_PP_NODE_166)
#                        define FB_BOOST_PP_NODE_162(p) FB_BOOST_PP_IIF(p##(162), FB_BOOST_PP_NODE_161, FB_BOOST_PP_NODE_163)
#                            define FB_BOOST_PP_NODE_161(p) FB_BOOST_PP_IIF(p##(161), 161, 162)
#                            define FB_BOOST_PP_NODE_163(p) FB_BOOST_PP_IIF(p##(163), 163, 164)
#                        define FB_BOOST_PP_NODE_166(p) FB_BOOST_PP_IIF(p##(166), FB_BOOST_PP_NODE_165, FB_BOOST_PP_NODE_167)
#                            define FB_BOOST_PP_NODE_165(p) FB_BOOST_PP_IIF(p##(165), 165, 166)
#                            define FB_BOOST_PP_NODE_167(p) FB_BOOST_PP_IIF(p##(167), 167, 168)
#                    define FB_BOOST_PP_NODE_172(p) FB_BOOST_PP_IIF(p##(172), FB_BOOST_PP_NODE_170, FB_BOOST_PP_NODE_174)
#                        define FB_BOOST_PP_NODE_170(p) FB_BOOST_PP_IIF(p##(170), FB_BOOST_PP_NODE_169, FB_BOOST_PP_NODE_171)
#                            define FB_BOOST_PP_NODE_169(p) FB_BOOST_PP_IIF(p##(169), 169, 170)
#                            define FB_BOOST_PP_NODE_171(p) FB_BOOST_PP_IIF(p##(171), 171, 172)
#                        define FB_BOOST_PP_NODE_174(p) FB_BOOST_PP_IIF(p##(174), FB_BOOST_PP_NODE_173, FB_BOOST_PP_NODE_175)
#                            define FB_BOOST_PP_NODE_173(p) FB_BOOST_PP_IIF(p##(173), 173, 174)
#                            define FB_BOOST_PP_NODE_175(p) FB_BOOST_PP_IIF(p##(175), 175, 176)
#                define FB_BOOST_PP_NODE_184(p) FB_BOOST_PP_IIF(p##(184), FB_BOOST_PP_NODE_180, FB_BOOST_PP_NODE_188)
#                    define FB_BOOST_PP_NODE_180(p) FB_BOOST_PP_IIF(p##(180), FB_BOOST_PP_NODE_178, FB_BOOST_PP_NODE_182)
#                        define FB_BOOST_PP_NODE_178(p) FB_BOOST_PP_IIF(p##(178), FB_BOOST_PP_NODE_177, FB_BOOST_PP_NODE_179)
#                            define FB_BOOST_PP_NODE_177(p) FB_BOOST_PP_IIF(p##(177), 177, 178)
#                            define FB_BOOST_PP_NODE_179(p) FB_BOOST_PP_IIF(p##(179), 179, 180)
#                        define FB_BOOST_PP_NODE_182(p) FB_BOOST_PP_IIF(p##(182), FB_BOOST_PP_NODE_181, FB_BOOST_PP_NODE_183)
#                            define FB_BOOST_PP_NODE_181(p) FB_BOOST_PP_IIF(p##(181), 181, 182)
#                            define FB_BOOST_PP_NODE_183(p) FB_BOOST_PP_IIF(p##(183), 183, 184)
#                    define FB_BOOST_PP_NODE_188(p) FB_BOOST_PP_IIF(p##(188), FB_BOOST_PP_NODE_186, FB_BOOST_PP_NODE_190)
#                        define FB_BOOST_PP_NODE_186(p) FB_BOOST_PP_IIF(p##(186), FB_BOOST_PP_NODE_185, FB_BOOST_PP_NODE_187)
#                            define FB_BOOST_PP_NODE_185(p) FB_BOOST_PP_IIF(p##(185), 185, 186)
#                            define FB_BOOST_PP_NODE_187(p) FB_BOOST_PP_IIF(p##(187), 187, 188)
#                        define FB_BOOST_PP_NODE_190(p) FB_BOOST_PP_IIF(p##(190), FB_BOOST_PP_NODE_189, FB_BOOST_PP_NODE_191)
#                            define FB_BOOST_PP_NODE_189(p) FB_BOOST_PP_IIF(p##(189), 189, 190)
#                            define FB_BOOST_PP_NODE_191(p) FB_BOOST_PP_IIF(p##(191), 191, 192)
#        define FB_BOOST_PP_NODE_224(p) FB_BOOST_PP_IIF(p##(224), FB_BOOST_PP_NODE_208, FB_BOOST_PP_NODE_240)
#            define FB_BOOST_PP_NODE_208(p) FB_BOOST_PP_IIF(p##(208), FB_BOOST_PP_NODE_200, FB_BOOST_PP_NODE_216)
#                define FB_BOOST_PP_NODE_200(p) FB_BOOST_PP_IIF(p##(200), FB_BOOST_PP_NODE_196, FB_BOOST_PP_NODE_204)
#                    define FB_BOOST_PP_NODE_196(p) FB_BOOST_PP_IIF(p##(196), FB_BOOST_PP_NODE_194, FB_BOOST_PP_NODE_198)
#                        define FB_BOOST_PP_NODE_194(p) FB_BOOST_PP_IIF(p##(194), FB_BOOST_PP_NODE_193, FB_BOOST_PP_NODE_195)
#                            define FB_BOOST_PP_NODE_193(p) FB_BOOST_PP_IIF(p##(193), 193, 194)
#                            define FB_BOOST_PP_NODE_195(p) FB_BOOST_PP_IIF(p##(195), 195, 196)
#                        define FB_BOOST_PP_NODE_198(p) FB_BOOST_PP_IIF(p##(198), FB_BOOST_PP_NODE_197, FB_BOOST_PP_NODE_199)
#                            define FB_BOOST_PP_NODE_197(p) FB_BOOST_PP_IIF(p##(197), 197, 198)
#                            define FB_BOOST_PP_NODE_199(p) FB_BOOST_PP_IIF(p##(199), 199, 200)
#                    define FB_BOOST_PP_NODE_204(p) FB_BOOST_PP_IIF(p##(204), FB_BOOST_PP_NODE_202, FB_BOOST_PP_NODE_206)
#                        define FB_BOOST_PP_NODE_202(p) FB_BOOST_PP_IIF(p##(202), FB_BOOST_PP_NODE_201, FB_BOOST_PP_NODE_203)
#                            define FB_BOOST_PP_NODE_201(p) FB_BOOST_PP_IIF(p##(201), 201, 202)
#                            define FB_BOOST_PP_NODE_203(p) FB_BOOST_PP_IIF(p##(203), 203, 204)
#                        define FB_BOOST_PP_NODE_206(p) FB_BOOST_PP_IIF(p##(206), FB_BOOST_PP_NODE_205, FB_BOOST_PP_NODE_207)
#                            define FB_BOOST_PP_NODE_205(p) FB_BOOST_PP_IIF(p##(205), 205, 206)
#                            define FB_BOOST_PP_NODE_207(p) FB_BOOST_PP_IIF(p##(207), 207, 208)
#                define FB_BOOST_PP_NODE_216(p) FB_BOOST_PP_IIF(p##(216), FB_BOOST_PP_NODE_212, FB_BOOST_PP_NODE_220)
#                    define FB_BOOST_PP_NODE_212(p) FB_BOOST_PP_IIF(p##(212), FB_BOOST_PP_NODE_210, FB_BOOST_PP_NODE_214)
#                        define FB_BOOST_PP_NODE_210(p) FB_BOOST_PP_IIF(p##(210), FB_BOOST_PP_NODE_209, FB_BOOST_PP_NODE_211)
#                            define FB_BOOST_PP_NODE_209(p) FB_BOOST_PP_IIF(p##(209), 209, 210)
#                            define FB_BOOST_PP_NODE_211(p) FB_BOOST_PP_IIF(p##(211), 211, 212)
#                        define FB_BOOST_PP_NODE_214(p) FB_BOOST_PP_IIF(p##(214), FB_BOOST_PP_NODE_213, FB_BOOST_PP_NODE_215)
#                            define FB_BOOST_PP_NODE_213(p) FB_BOOST_PP_IIF(p##(213), 213, 214)
#                            define FB_BOOST_PP_NODE_215(p) FB_BOOST_PP_IIF(p##(215), 215, 216)
#                    define FB_BOOST_PP_NODE_220(p) FB_BOOST_PP_IIF(p##(220), FB_BOOST_PP_NODE_218, FB_BOOST_PP_NODE_222)
#                        define FB_BOOST_PP_NODE_218(p) FB_BOOST_PP_IIF(p##(218), FB_BOOST_PP_NODE_217, FB_BOOST_PP_NODE_219)
#                            define FB_BOOST_PP_NODE_217(p) FB_BOOST_PP_IIF(p##(217), 217, 218)
#                            define FB_BOOST_PP_NODE_219(p) FB_BOOST_PP_IIF(p##(219), 219, 220)
#                        define FB_BOOST_PP_NODE_222(p) FB_BOOST_PP_IIF(p##(222), FB_BOOST_PP_NODE_221, FB_BOOST_PP_NODE_223)
#                            define FB_BOOST_PP_NODE_221(p) FB_BOOST_PP_IIF(p##(221), 221, 222)
#                            define FB_BOOST_PP_NODE_223(p) FB_BOOST_PP_IIF(p##(223), 223, 224)
#            define FB_BOOST_PP_NODE_240(p) FB_BOOST_PP_IIF(p##(240), FB_BOOST_PP_NODE_232, FB_BOOST_PP_NODE_248)
#                define FB_BOOST_PP_NODE_232(p) FB_BOOST_PP_IIF(p##(232), FB_BOOST_PP_NODE_228, FB_BOOST_PP_NODE_236)
#                    define FB_BOOST_PP_NODE_228(p) FB_BOOST_PP_IIF(p##(228), FB_BOOST_PP_NODE_226, FB_BOOST_PP_NODE_230)
#                        define FB_BOOST_PP_NODE_226(p) FB_BOOST_PP_IIF(p##(226), FB_BOOST_PP_NODE_225, FB_BOOST_PP_NODE_227)
#                            define FB_BOOST_PP_NODE_225(p) FB_BOOST_PP_IIF(p##(225), 225, 226)
#                            define FB_BOOST_PP_NODE_227(p) FB_BOOST_PP_IIF(p##(227), 227, 228)
#                        define FB_BOOST_PP_NODE_230(p) FB_BOOST_PP_IIF(p##(230), FB_BOOST_PP_NODE_229, FB_BOOST_PP_NODE_231)
#                            define FB_BOOST_PP_NODE_229(p) FB_BOOST_PP_IIF(p##(229), 229, 230)
#                            define FB_BOOST_PP_NODE_231(p) FB_BOOST_PP_IIF(p##(231), 231, 232)
#                    define FB_BOOST_PP_NODE_236(p) FB_BOOST_PP_IIF(p##(236), FB_BOOST_PP_NODE_234, FB_BOOST_PP_NODE_238)
#                        define FB_BOOST_PP_NODE_234(p) FB_BOOST_PP_IIF(p##(234), FB_BOOST_PP_NODE_233, FB_BOOST_PP_NODE_235)
#                            define FB_BOOST_PP_NODE_233(p) FB_BOOST_PP_IIF(p##(233), 233, 234)
#                            define FB_BOOST_PP_NODE_235(p) FB_BOOST_PP_IIF(p##(235), 235, 236)
#                        define FB_BOOST_PP_NODE_238(p) FB_BOOST_PP_IIF(p##(238), FB_BOOST_PP_NODE_237, FB_BOOST_PP_NODE_239)
#                            define FB_BOOST_PP_NODE_237(p) FB_BOOST_PP_IIF(p##(237), 237, 238)
#                            define FB_BOOST_PP_NODE_239(p) FB_BOOST_PP_IIF(p##(239), 239, 240)
#                define FB_BOOST_PP_NODE_248(p) FB_BOOST_PP_IIF(p##(248), FB_BOOST_PP_NODE_244, FB_BOOST_PP_NODE_252)
#                    define FB_BOOST_PP_NODE_244(p) FB_BOOST_PP_IIF(p##(244), FB_BOOST_PP_NODE_242, FB_BOOST_PP_NODE_246)
#                        define FB_BOOST_PP_NODE_242(p) FB_BOOST_PP_IIF(p##(242), FB_BOOST_PP_NODE_241, FB_BOOST_PP_NODE_243)
#                            define FB_BOOST_PP_NODE_241(p) FB_BOOST_PP_IIF(p##(241), 241, 242)
#                            define FB_BOOST_PP_NODE_243(p) FB_BOOST_PP_IIF(p##(243), 243, 244)
#                        define FB_BOOST_PP_NODE_246(p) FB_BOOST_PP_IIF(p##(246), FB_BOOST_PP_NODE_245, FB_BOOST_PP_NODE_247)
#                            define FB_BOOST_PP_NODE_245(p) FB_BOOST_PP_IIF(p##(245), 245, 246)
#                            define FB_BOOST_PP_NODE_247(p) FB_BOOST_PP_IIF(p##(247), 247, 248)
#                    define FB_BOOST_PP_NODE_252(p) FB_BOOST_PP_IIF(p##(252), FB_BOOST_PP_NODE_250, FB_BOOST_PP_NODE_254)
#                        define FB_BOOST_PP_NODE_250(p) FB_BOOST_PP_IIF(p##(250), FB_BOOST_PP_NODE_249, FB_BOOST_PP_NODE_251)
#                            define FB_BOOST_PP_NODE_249(p) FB_BOOST_PP_IIF(p##(249), 249, 250)
#                            define FB_BOOST_PP_NODE_251(p) FB_BOOST_PP_IIF(p##(251), 251, 252)
#                        define FB_BOOST_PP_NODE_254(p) FB_BOOST_PP_IIF(p##(254), FB_BOOST_PP_NODE_253, FB_BOOST_PP_NODE_255)
#                            define FB_BOOST_PP_NODE_253(p) FB_BOOST_PP_IIF(p##(253), 253, 254)
#                            define FB_BOOST_PP_NODE_255(p) FB_BOOST_PP_IIF(p##(255), 255, 256)
#
# endif
