.TH odbc.ini 5 "Thu 27 Jun 2013" "version 2.3.2" "unixODBC manual pages"

.SH NAME
/etc/odbc.ini, $HOME/.odbc.ini - unixODBC data sources configuration

.SH DESCRIPTION
.B /etc/odbc.ini
is text configuration file for the system wide ODBC data sources (i. e. database
connections).
.B $HOME/.odbc.ini
contains the configuration for user-specific data sources.

.SH "SEE ALSO"
.BR odbcinst (1),
.BR isql (1),
.BR odbcinst.ini (5)

.SH AUTHORS
The authors of unixODBC are Peter Harvey <\fIpharvey@codebydesign.com\fR> and
Nick Gorham <\fInick@lurcher.org\fR>. For the full list of contributors see the
AUTHORS file.

.SH COPYRIGHT
unixODBC is licensed under the GNU Lesser General Public License. For details
about the license, see the COPYING file.
