#!/bin/sh
#
#  The contents of this file are subject to the Initial
#  Developer's Public License Version 1.0 (the "License");
#  you may not use this file except in compliance with the
#  License. You may obtain a copy of the License at
#  http://www.ibphoenix.com/main.nfs?a=ibphoenix&page=ibp_idpl.
#
#  Software distributed under the License is distributed AS IS,
#  WITHOUT WARRANTY OF ANY KIND, either express or implied.
#  See the License for the specific language governing rights
#  and limitations under the License.
#
#  The Original Code was created by Alexander Peshkov on 8-Jan-2013
#  for the Firebird Open Source RDBMS project.
#
#  Copyright (c) 2013 Alexander Peshkov <peshkoff@mail.ru>
#  and all contributors signed below.
#
#  All Rights Reserved.
#  Contributor(s): ______________________________________.
#
#
# Script to check correctness of interface definition in firebird.
# Does not pretend to be abs. precise, but definitely helps to find bugs.
# Typical use (src/include/firebird):
#	checkIface *.h
#

awk -f - ${*} <<EOS
BEGINFILE {v=0; print FILENAME;}
/class/ {v=0;}
/virtual/ {v++;}
/FB_[A-Z0-9_]+_VERSION/ {
	n = 0 + \$5;
	if (\$2 == "FB_VERSIONED_VERSION")
		n = 0 + \$3;
	if (v != n)
		printf "%s: %d != %d\n", \$2, v, n;
}
EOS
