{        SYBEICONVI,        EXINFO,	"WARNING! Some character(s) could not be converted into client's character set. Unconverted bytes were changed to question marks ('?')."},
{        SYBEICONVO,        EXUSER,	"Error converting client characters into server's character set. Some character(s) could not be converted."},
{        SYBEAAMT,       EXPROGRAM,	"User attempted a dbaltbind() with mismatched column and variable types."},
{        SYBEABMT,       EXPROGRAM,	"User attempted a dbbind() with mismatched column and variable types."},
{        SYBEABNC,       EXPROGRAM,	"Attempt to bind to a non-existent column."},
{        SYBEABNP,       EXPROGRAM,	"Attempt to bind using NULL pointers."},
{        SYBEABNV,       EXPROGRAM,	"Attempt to bind to a NULL program variable."},
{        SYBEACNV,    EXCONVERSION,	"Attemp to do conversion with NULL destination variable."},
{        SYBEADST,   EXCONSISTENCY,	"Error in attempting to determine the size of a pair of translation tables."},
{        SYBEAICF,   EXCONSISTENCY,	"Error in attempting to install custom format."},
{        SYBEALTT,   EXCONSISTENCY,	"Error in attempting to load a pair of translation tables."},
{        SYBEAOLF,      EXRESOURCE,	"Error in attempting to open a localization file."},
{        SYBEAPCT,   EXCONSISTENCY,	"Error in attempting to perform a character-set translation."},
{        SYBEAPUT,       EXPROGRAM,	"Attempt to print unknown token."},
{        SYBEARDI,      EXRESOURCE,	"Error in attempting to read datetime information from a localization file."},
{        SYBEARDL,      EXRESOURCE,	"Error in attempting to read the dblib.loc localization file."},
{        SYBEASEC,       EXPROGRAM,	"Attempt to send an empty command buffer to the SQL Server."},
{        SYBEASNL,       EXPROGRAM,	"Attempt to set fields in a null loginrec."},
{        SYBEASTF,               1,	"VMS: Unable to setmode for control_c ast."},
{        SYBEASTL,       EXPROGRAM,	"Synchronous IO attempted at AST level."},
{        SYBEASUL,       EXPROGRAM,	"Attempt to set unknown loginrec field."},
{     SYBEATTNACK,               1,	"Timed out waiting for server to acknowledge attention."},
{        SYBEAUTN,       EXPROGRAM,	"Attempt to update the timestamp of a table which has no timestamp column."},
{       SYBEBADPK,          EXINFO,	"Packet size of %1! not supported. -- size of %2! used instead."},
{     SYBEBADTYPE,               1,	"Illegal value for type parameter  given to %1!."},
{        SYBEBBCI,          EXINFO,	"Batch successfully bulk-copied to SQL Server."},
{        SYBEBBFL,               1,	"-001- Batch failed in bulk-copy to SQL Server."},
{         SYBEBBL,       EXPROGRAM,	"Bad bindlen parameter passed to dbsetnull()."},
{        SYBEBCBC,       EXPROGRAM,	"bcp_columns() must be called before bcp_colfmt() and bcp_colfmt_ps()."},
{      SYBEBCBNPR,       EXPROGRAM,	"bcp_bind(): if varaddr is NULL, prefixlen must be 0 and no terminator should be specified."},
{     SYBEBCBNTYP,       EXPROGRAM,	"bcp_bind(): if varaddr is NULL and varlen greater than 0, the table column type must be SYBTEXT or SYBIMAGE and the program variable type must be SYBTEXT, SYBCHAR, SYBIMAGE or SYBBINARY."},
{     SYBEBCBPREF,       EXPROGRAM,	"Illegal prefix length. Legal values are 0, 1, 2 or 4."},
{        SYBEBCFO,          EXUSER,	"Bcp host-files must contain at least one column."},
{      SYBEBCHLEN,       EXPROGRAM,	"host_collen should be greater than or equal to -1."},
{        SYBEBCIS,   EXCONSISTENCY,	"Attempt to bulk-copy an illegally-sized column value to the SQL Server."},
{        SYBEBCIT,       EXPROGRAM,	"It's illegal to use BCP terminators with program variables other than SYBCHAR, SYBBINARY, SYBTEXT, or SYBIMAGE."},
{    SYBEBCITBLEN,       EXPROGRAM,	"bcp_init(): tblname parameter is too long."},
{     SYBEBCITBNM,       EXPROGRAM,	"bcp_init(): tblname parameter cannot be NULL."},
{      SYBEBCMTXT,       EXPROGRAM,	"bcp_moretext() may be used only when there is at least one text or image column in the server table."},
{        SYBEBCNL,      EXNONFATAL,	"Negative length-prefix found in BCP data-file."},
{        SYBEBCNN,          EXUSER,	"Attempt to bulk-copy a NULL value into Server column 0,  which does not accept NULL values."},
{        SYBEBCNT,          EXUSER,	"Attempt to use Bulk Copy with a non-existent Server table."},
{        SYBEBCOR,   EXCONSISTENCY,	"Attempt to bulk-copy an oversized row to the SQL Server."},
{        SYBEBCPB,       EXPROGRAM,	"bcp_bind(), bcp_moretext() and bcp_sendrow() may NOT be used after bcp_init() has been passed a non-NULL input file name."},
{     SYBEBCPCTYP,       EXPROGRAM,	"bcp_colfmt(): If table_colnum is 0, host_type cannot be 0."},
{        SYBEBCPI,       EXPROGRAM,	"bcp_init() must be called before any other bcp routines."},
{        SYBEBCPN,       EXPROGRAM,	"bcp_bind(), bcp_collen(), bcp_colptr(), bcp_moretext() and bcp_sendrow() may be used only after bcp_init() has been called with the copy direction set to DB_IN."},
{      SYBEBCPOPT,               1,	"The  option cannot be called while a bulk copy operation is progress."},
{      SYBEBCPREC,      EXNONFATAL,	"Column %1!: Illegal precision value encountered."},
{      SYBEBCPREF,       EXPROGRAM,	"Illegal prefix length. Legal values are -1, 0, 1, 2 or 4."},
{        SYBEBCRE,      EXNONFATAL,	"IO error while reading bcp data-file."},
{        SYBEBCRO,          EXINFO,	"The BCP hostfile '' contains only 0 rows. It was impossible to read the requested 0 rows."},
{        SYBEBCSA,          EXUSER,	"The BCP hostfile '' contains only 0 rows. Skipping all of these rows is not allowed."},
{       SYBEBCSET,   EXCONSISTENCY,	"Unknown character-set encountered."},
{        SYBEBCSI,       EXPROGRAM,	"Host-file columns may be skipped only when copying INto the Server."},
{    SYBEBCSNDROW,       EXPROGRAM,	"bcp_sendrow() may NOT be called unless all text data for the previous row has been sent using bcp_moretext()."},
{     SYBEBCSNTYP,       EXPROGRAM,	"column number %1!: if varaddr is NULL and varlen greater than 0, the table column type must be SYBTEXT or SYBIMAGE and the program variable type must be SYBTEXT, SYBCHAR, SYBIMAGE or SYBBINARY."},
{        SYBEBCUC,      EXRESOURCE,	"Bcp: Unable to close host data-file."},
{        SYBEBCUO,      EXRESOURCE,	"Bcp: Unable to open host data-file."},
{        SYBEBCVH,       EXPROGRAM,	"bcp_exec() may be called only after bcp_init() has been passed a valid host file."},
{      SYBEBCVLEN,       EXPROGRAM,	"varlen should be greater than or equal to -1."},
{        SYBEBCWE,      EXNONFATAL,	"IO error while writing bcp data-file."},
{        SYBEBDIO,       EXPROGRAM,	"Bad bulk-copy direction.  Must be either IN or OUT."},
{        SYBEBEOF,      EXNONFATAL,	"Unexpected EOF encountered in BCP data-file."},
{        SYBEBIHC,       EXPROGRAM,	"Incorrect host-column number found in bcp format-file."},
{        SYBEBIVI,       EXPROGRAM,	"bcp_columns(), bcp_colfmt() and bcp_colfmt_ps() may be used only after bcp_init() has been passed a valid input file."},
{        SYBEBNCR,       EXPROGRAM,	"Attempt to bind user variable to a non-existent compute row."},
{        SYBEBNUM,       EXPROGRAM,	"Bad numbytes parameter passed to dbstrcpy()."},
{        SYBEBOOL,               1,	"Boolean parameters must be TRUE or FALSE."},
{        SYBEBPKS,       EXPROGRAM,	"In DBSETLPACKET(), the packet size parameter must be between 0 and 999999."},
{       SYBEBPREC,       EXPROGRAM,	"Illegal precision specified."},
{  SYBEBPROBADDEF,   EXCONSISTENCY,	"bcp protocol error: illegal default column id received."},
{  SYBEBPROBADLEN,               1,	"bcp protocol error: illegal datatype length received."},
{ SYBEBPROBADPREC,               1,	"bcp protocol error: illegal precision value received."},
{  SYBEBPROBADSCL,               1,	"bcp protocol error: illegal scale value received."},
{  SYBEBPROBADTYP,               1,	"bcp protocol error: unknown column datatype."},
{     SYBEBPROCOL,   EXCONSISTENCY,	"bcp protocol error: returned column count differs from the actual number of columns received."},
{     SYBEBPRODEF,   EXCONSISTENCY,	"bcp protocol error: expected default information and got none."},
{   SYBEBPRODEFID,   EXCONSISTENCY,	"bcp protocol error: default column id and actual column id are not same."},
{  SYBEBPRODEFTYP,   EXCONSISTENCY,	"bcp protocol error:  default value datatype differs from column datatype."},
{  SYBEBPROEXTDEF,   EXCONSISTENCY,	"bcp protocol error: more than one row of default information received."},
{  SYBEBPROEXTRES,   EXCONSISTENCY,	"bcp protocol error: unexpected set of results received."},
{   SYBEBPRONODEF,   EXCONSISTENCY,	"bcp protocol error:  default value received for column that does not have default."},
{  SYBEBPRONUMDEF,   EXCONSISTENCY,	"bcp protocol error: expected number of defaults differs from the actual number of defaults received."},
{        SYBEBRFF,      EXRESOURCE,	"IO error while reading bcp format-file."},
{      SYBEBSCALE,       EXPROGRAM,	"Illegal scale specified."},
{        SYBEBTMT,       EXPROGRAM,	"Attempt to send too much TEXT data via the bcp_moretext() call."},
{        SYBEBTOK,          EXCOMM,	"Bad token from SQL Server: Data-stream processing out of sync."},
{        SYBEBTYP,       EXPROGRAM,	"Unknown bind type passed to DB-LIBRARY function."},
{     SYBEBTYPSRV,       EXPROGRAM,	"Datatype is not supported by the server."},
{        SYBEBUCE,      EXRESOURCE,	"Bcp: Unable to close error-file."},
{        SYBEBUCF,       EXPROGRAM,	"Bcp: Unable to close format-file."},
{        SYBEBUDF,       EXPROGRAM,	"Bcp: Unrecognized datatype found in format-file."},
{        SYBEBUFF,       EXPROGRAM,	"Bcp: Unable to create format-file."},
{        SYBEBUFL,   EXCONSISTENCY,	"DB-LIBRARY internal error - send buffer length corrupted."},
{        SYBEBUOE,      EXRESOURCE,	"Bcp: Unable to open error-file."},
{        SYBEBUOF,       EXPROGRAM,	"Bcp: Unable to open format-file."},
{        SYBEBWEF,      EXNONFATAL,	"IO error while writing bcp error-file."},
{        SYBEBWFF,      EXRESOURCE,	"IO error while writing bcp format-file."},
{         SYBECAP,          EXCOMM,	"DB-Library capabilities not accepted by the Server."},
{      SYBECAPTYP,          EXCOMM,	"Unexpected capability type in CAPABILITY datastream."},
{        SYBECDNS,   EXCONSISTENCY,	"Datastream indicates that a compute column is derived from a non-existent select-list member."},
{     SYBECDOMAIN,    EXCONVERSION,	"Source field value is not within the domain of legal values."},
{   SYBECINTERNAL,    EXCONVERSION,	"Internal Conversion error."},
{        SYBECLOS,          EXCOMM,	"Error in closing network connection."},
{     SYBECLOSEIN,               1,	"Unable to close interface file."},
{        SYBECLPR,    EXCONVERSION,	"Data-conversion resulted in loss of precision."},
{        SYBECNOR,       EXPROGRAM,	"Column number out of range."},
{        SYBECNOV,    EXCONVERSION,	"Attempt to set variable to NULL resulted in overflow."},
{        SYBECOFL,    EXCONVERSION,	"Data-conversion resulted in overflow."},
{        SYBECONN,          EXCOMM,	"Unable to connect socket -- SQL Server is unavailable or does not exist."},
{        SYBECRNC,       EXPROGRAM,	"The current row is not a result of compute clause 0, so it is illegal to attempt to extract that data from this row."},
{      SYBECRSAGR,       EXPROGRAM,	"Aggregate functions are not allowed in a  cursor statement."},
{     SYBECRSBROL,       EXPROGRAM,	"Backward scrolling cannot be used in a  forward scrolling cursor."},
{    SYBECRSBSKEY,       EXPROGRAM,	"Keyset cannot be scrolled backward in mixed  cursors with a previous fetch type."},
{     SYBECRSBUFR,       EXPROGRAM,	"Row buffering should not be turned on when  using cursor APIs."},
{      SYBECRSDIS,       EXPROGRAM,	"Cursor statement contains one of the  disallowed phrases 'compute', 'union', 'for browse', or 'select into'."},
{    SYBECRSFLAST,       EXPROGRAM,	"Fetch type LAST requires fully keyset  driven cursors."},
{    SYBECRSFRAND,       EXPROGRAM,	"Fetch types RANDOM and RELATIVE can only be  used within the keyset of keyset driven  cursors."},
{    SYBECRSFROWN,       EXPROGRAM,	"Row number to be fetched is outside valid  range."},
{    SYBECRSFTYPE,      EXRESOURCE,	"Unknown fetch type."},
{      SYBECRSINV,       EXPROGRAM,	"Invalid cursor statement."},
{  SYBECRSINVALID,      EXRESOURCE,	"The cursor handle is invalid."},
{    SYBECRSMROWS,      EXRESOURCE,	"Multiple rows are returned, only one is expected."},
{   SYBECRSNOBIND,       EXPROGRAM,	"Cursor bind must be called prior to updating cursor."},
{  SYBECRSNOCOUNT,       EXPROGRAM,	"The DBNOCOUNT option should not be  turned on when doing updates or deletes with  dbcursor()."},
{   SYBECRSNOFREE,       EXPROGRAM,	"The DBNOAUTOFREE option should not be  turned on when using cursor APIs."},
{    SYBECRSNOIND,       EXPROGRAM,	"One of the tables involved in the cursor  statement does not have a unique index."},
{   SYBECRSNOKEYS,      EXRESOURCE,	"The entire keyset must be defined for KEYSET cursors."},
{    SYBECRSNOLEN,      EXRESOURCE,	"No unique index found."},
{   SYBECRSNOPTCC,      EXRESOURCE,	"No OPTCC was found."},
{   SYBECRSNORDER,      EXRESOURCE,	"The order of clauses must be from, where, and order by."},
{    SYBECRSNORES,       EXPROGRAM,	"Cursor statement generated no results."},
{  SYBECRSNOTABLE,      EXRESOURCE,	"Table name is NULL."},
{    SYBECRSNOUPD,       EXPROGRAM,	"Update or delete operation did not affect  any rows."},
{  SYBECRSNOWHERE,       EXPROGRAM,	"A WHERE clause is not allowed in a cursor  update or insert."},
{    SYBECRSNROWS,      EXRESOURCE,	"No rows returned, at least one is expected."},
{  SYBECRSNUNIQUE,      EXRESOURCE,	"No unique keys associated with this view."},
{      SYBECRSORD,       EXPROGRAM,	"Only fully keyset driven cursors can have 'order by', ' group by', or 'having' phrases."},
{       SYBECRSRO,       EXPROGRAM,	"Data locking or modifications cannot be  made in a READONLY cursor."},
{      SYBECRSSET,       EXPROGRAM,	"A SET clause is required for a cursor  update or insert."},
{      SYBECRSTAB,       EXPROGRAM,	"Table name must be determined in operations  involving data locking or modifications."},
{    SYBECRSUPDNB,       EXPROGRAM,	"Update or insert operations cannot use bind  variables when binding type is NOBIND."},
{   SYBECRSUPDTAB,       EXPROGRAM,	"Update or insert operations using bind  variables require single table cursors."},
{      SYBECRSVAR,      EXRESOURCE,	"There is no valid address associated with this bind."},
{     SYBECRSVIEW,       EXPROGRAM,	"A view cannot be joined with another table  or a view in a cursor statement."},
{    SYBECRSVIIND,       EXPROGRAM,	"The view used in the cursor statement does  not include all the unique index columns of  the underlying tables."},
{          SYBECS,               1,	"-004- cs context Error."},
{        SYBECSYN,    EXCONVERSION,	"Attempt to convert data stopped by syntax error in source field."},
{        SYBECUFL,    EXCONVERSION,	"Data-conversion resulted in underflow."},
{        SYBECWLL,               1,	"Attempt to set column width less than 1."},
{        SYBEDBPS,      EXRESOURCE,	"Maximum number of DBPROCESSes already allocated."},
{         SYBEDCL,               1,	"-004- DCL Error."},
{        SYBEDDNE,          EXINFO,	"DBPROCESS is dead or not enabled."},
{        SYBEDIVZ,          EXUSER,	"Attempt to divide by $0.00 in function %1!."},
{        SYBEDNTI,       EXPROGRAM,	"Attempt to use dbtxtsput() to put a new text-timestamp into a column whose datatype is neither SYBTEXT nor SYBIMAGE."},
{        SYBEDPOR,       EXPROGRAM,	"Out-of-range datepart constant."},
{        SYBEDVOR,       EXPROGRAM,	"Day values must be between 1 and 7."},
{        SYBEECAN,          EXINFO,	"Attempted to cancel unrequested event notification."},
{        SYBEECRT,               1,	"Must call dbregdefine() before dbregcreate()."},
{        SYBEEINI,          EXINFO,	"Must call dbreginit() before dbregraise()."},
{        SYBEEQVA,               1,	"Error in queueing VMS AST routine."},
{    SYBEERRLABEL,               1,	"An illegal value was returned from the security label handler."},
{        SYBEESSL,               1,	"Login security level entered does not agree with operating system level."},
{         SYBEETD,       EXPROGRAM,	"Failure to send the expected amount of  TEXT or IMAGE data via dbmoretext()."},
{        SYBEEUNR,          EXCOMM,	"Unsolicited event notification received."},
{        SYBEEVOP,          EXINFO,	"Called dbregwatch() with a bad options parameter."},
{        SYBEEVST,          EXINFO,	"Must initiate a transaction before calling dbregparam()."},
{        SYBEFCON,          EXCOMM,	"SQL Server connection failed."},
{        SYBEFENC,               1,	"Password Encryption failed."},
{        SYBEFGTL,               1,	"Bcp: Row number of the first row to be copied cannot be greater than the row number for the last row to be copied."},
{       SYBEFMODE,               1,	"ReadWriteAppend mode denied on file."},
{        SYBEFRES,         EXFATAL,	"Challenge-Response function failed."},
{        SYBEFSHD,      EXRESOURCE,	"Error in attempting to find the Sybase home directory."},
{        SYBEFUNC,       EXPROGRAM,	"Functionality not supported at the specified version level."},
{       SYBEGENOS,               1,	"General Operating System Error."},
{         SYBEICN,       EXPROGRAM,	"Invalid computeid or compute column number."},
{        SYBEIDCL,   EXCONSISTENCY,	"Illegal datetime column length returned by DataServer. Legal datetime lengths are 4 and 8 bytes."},
{      SYBEIDECCL,   EXCONSISTENCY,	"Invalid decimal column length returned by the server."},
{        SYBEIFCL,   EXCONSISTENCY,	"Illegal floating-point column length returned by DataServer. Legal floating-point lengths are 4 and 8 bytes."},
{        SYBEIFNB,       EXPROGRAM,	"Illegal field number passed to bcp_control()."},
{        SYBEIICL,   EXCONSISTENCY,	"Illegal integer column length returned by SQL Server. Legal integer lengths are 1, 2, and 4 bytes."},
{        SYBEIMCL,   EXCONSISTENCY,	"Illegal money column length returned by DataServer. Legal money lengths are 4 and 8 bytes."},
{        SYBEINLN,          EXUSER,	"Interface file: unexpected end-of-line."},
{        SYBEINTF,          EXUSER,	"Server name not found in interface file."},
{      SYBEINUMCL,   EXCONSISTENCY,	"Invalid numeric column length returned by the server."},
{         SYBEIPV,          EXINFO,	"%1! is an illegal value for the %2! parameter of %3!."},
{        SYBEISOI,   EXCONSISTENCY,	"Invalid sort-order information found."},
{    SYBEISRVPREC,   EXCONSISTENCY,	"Illegal precision value returned by the server."},
{     SYBEISRVSCL,   EXCONSISTENCY,	"Illegal scale value returned by the server."},
{        SYBEITIM,       EXPROGRAM,	"Illegal timeout value specified."},
{       SYBEIVERS,       EXPROGRAM,	"Illegal version level specified."},
{        SYBEKBCI,          EXINFO,	"Bcp: 1000 rows sent to SQL Server."},
{        SYBEKBCO,          EXINFO,	"1000 rows successfully bulk-copied to host-file."},
{       SYBELBLEN,               1,	"Security labels should be less than 256 characters long."},
{         SYBEMEM,      EXRESOURCE,	"Unable to allocate sufficient memory."},
{         SYBEMOV,          EXUSER,	"Money arithmetic resulted in overflow in function %1!."},
{        SYBEMPLL,          EXUSER,	"Attempt to set maximum number of DBPROCESSes lower than 1."},
{        SYBEMVOR,       EXPROGRAM,	"Month values must be between 1 and 12."},
{        SYBENBUF,          EXINFO,	"called dbsendpassthru() with a NULL buf pointer."},
{        SYBENBVP,       EXPROGRAM,	"Cannot pass dbsetnull() a NULL bindval pointer."},
{         SYBENDC,       EXPROGRAM,	"Cannot have negative component in date in numeric form."},
{        SYBENDTP,       EXPROGRAM,	"Called dbdatecrack() with a NULL datetime  parameter."},
{         SYBENEG,          EXCOMM,	"Negotiated login attempt failed."},
{        SYBENEHA,               1,	"Called dbreghandle() with a NULL handler parameter."},
{        SYBENHAN,          EXINFO,	"called dbrecvpassthru() with a NULL handler parameter."},
{        SYBENLNL,               1,	"Program not linked with specified network library."},
{        SYBENMOB,       EXPROGRAM,	"No such member of 'order by' clause."},
{        SYBENOEV,          EXINFO,	"dbpoll() cannot be called if registered procedure notifications have been disabled."},
{        SYBENOTI,               1,	"No event handler installed."},
{     SYBENOVALUE,               1,	"Security labels require both a name and a value."},
{        SYBENPRM,       EXPROGRAM,	"NULL parameter not allowed for this dboption."},
{        SYBENSIP,       EXPROGRAM,	"Negative starting index passed to dbstrcpy()."},
{        SYBENTLL,          EXUSER,	"Name too long for loginrec field."},
{        SYBENTST,               1,	"The file being opened must be a stream_lf."},
{        SYBENTTN,       EXPROGRAM,	"Attempt to use dbtxtsput() to put a new text-timestamp into a non-existent data row."},
{        SYBENULL,          EXINFO,	"NULL DBPROCESS pointer passed to DB-Library."},
{        SYBENULP,       EXPROGRAM,	"Called  with a NULL  parameter."},
{         SYBENUM,               1,	"Incorrect number of arguments given  to DB-Library."},
{        SYBENXID,      EXNONFATAL,	"The Server did not grant us a distributed-transaction ID."},
{        SYBEONCE,       EXPROGRAM,	"Function can be called only once."},
{         SYBEOOB,          EXCOMM,	"Error in sending out-of-band data to SQL Server."},
{        SYBEOPIN,      EXNONFATAL,	"Could not open interface file."},
{        SYBEOPNA,      EXNONFATAL,	"The textimage facility is available only when using a SQL Server whose version number is 4.0 or greater."},
{       SYBEOPTNO,               1,	"Option is not allowed or is unreconized."},
{        SYBEOREN,          EXINFO,	"Warning: an out-of-range error-number was encountered in dblib.loc. The maximum permissible error-number is defined as DBERRCOUNT in sybdb.h."},
{        SYBEORPF,          EXUSER,	"Attempt to set remote password would overflow the login-record's remote-password field."},
{        SYBEOSSL,               1,	"Operating system login level not in range of Secure SQL Server."},
{        SYBEPAGE,               1,	"wrong resource type or length given for  dbpage() operation."},
{        SYBEPOLL,          EXINFO,	"Only one dbpoll() can be active at a time."},
{        SYBEPRTF,          EXINFO,	"dbtracestring() may only be called from a printfunc()."},
{         SYBEPWD,          EXUSER,	"Incorrect password."},
{        SYBERDCN,    EXCONVERSION,	"Requested data-conversion does not exist."},
{        SYBERDNR,       EXPROGRAM,	"Attempt to retrieve data from a non-existent row."},
{        SYBEREAD,          EXCOMM,	"Read from SQL Server failed."},
{        SYBERESP,       EXPROGRAM,	"Response function address passed to dbresponse() must be non-NULL."},
{       SYBERFILE,               1,	"Can not open resource file."},
{        SYBERPCS,          EXINFO,	"Must call dbrpcinit() before dbrpcparam()."},
{        SYBERPIL,       EXPROGRAM,	"It is illegal to pass -1 to dbrpcparam() for the datalen of parameters which are of type SYBCHAR, SYBVARCHAR, SYBBINARY, or SYBVARBINARY."},
{        SYBERPNA,      EXNONFATAL,	"The RPC facility is available only when using a SQL Server whose version number is 4.0 or greater."},
{        SYBERPND,       EXPROGRAM,	"Attempt to initiate a new SQL Server operation with results pending."},
{      SYBERPNULL,       EXPROGRAM,	"value parameter for dbprcparam() can be NULL, only if the datalen parameter is 0."},
{     SYBERPTXTIM,       EXPROGRAM,	"RPC parameters cannot be of type TextImage."},
{        SYBERPUL,       EXPROGRAM,	"When passing a SYBINTN, SYBDATETIMN, SYBMONEYN, or SYBFLTN parameter via dbrpcparam(), it's necessary to specify the parameter's maximum or actual length, so that DB-Library can recognize it as a SYBINT1, SYBINT2, SYBINT4, SYBMONEY, or SYBMONEY4, etc."},
{        SYBERTCC,       EXPROGRAM,	"dbreadtext() may not be used to receive the results of a query which contains a COMPUTE clause."},
{        SYBERTSC,       EXPROGRAM,	"dbreadtext() may only be used to receive the results of a query which contains a single result column."},
{       SYBERTYPE,               1,	"Invalid resource type given to DB-Library."},
{        SYBERXID,      EXNONFATAL,	"The Server did not recognize our distributed-transaction ID."},
{      SYBESECURE,       EXPROGRAM,	"Secure Server function not supported in this version."},
{        SYBESEFA,       EXPROGRAM,	"DBSETNOTIFS cannot be called if connections are present."},
{        SYBESEOF,          EXCOMM,	"Unexpected EOF from SQL Server."},
{        SYBESFOV,       EXPROGRAM,	"dbsafestr() overflowed its destination buffer."},
{        SYBESLCT,               1,	"Could not select or copy field specified."},
{        SYBESMSG,        EXSERVER,	"General SQL Server error: Check messages from the SQL Server."},
{        SYBESOCK,          EXCOMM,	"Unable to open socket."},
{        SYBESPID,       EXPROGRAM,	"Called dbspid() with a NULL dbproc."},
{        SYBESYNC,          EXCOMM,	"Read attempted while out of synchronization with SQL Server."},
{        SYBETEXS,          EXINFO,	"Called dbmoretext() with a bad size parameter."},
{        SYBETIME,          EXTIME,	"SQL Server connection timed out."},
{        SYBETMCF,       EXPROGRAM,	"Attempt to install too many custom formats via dbfmtinstall()."},
{        SYBETMTD,       EXPROGRAM,	"Attempt to send too much TEXT data via the dbmoretext() call."},
{        SYBETPAR,       EXPROGRAM,	"No SYBTEXT or SYBIMAGE parameters were defined."},
{        SYBETPTN,          EXUSER,	"Syntax error: only two periods are permitted in table names."},
{        SYBETRAC,          EXINFO,	"Attempted to turn off a trace flag that was not on."},
{        SYBETRAN,          EXINFO,	"DBPROCESS is being used for another transaction."},
{        SYBETRAS,          EXINFO,	"DB-Library internal error - trace structure not found."},
{        SYBETRSN,          EXINFO,	"Bad numbytes parameter passed to dbtracestring()."},
{        SYBETSIT,          EXINFO,	"Attempt to call dbtsput() with an invalid timestamp."},
{         SYBETTS,          EXUSER,	"The table which bulk-copy is attempting to copy to a host-file is shorter than the number of rows which bulk-copy was instructed to skip."},
{        SYBETYPE,          EXINFO,	"Invalid argument type given to DB-Library."},
{        SYBEUACS,               1,	"VMS: Unable to assign channel to sys$command."},
{        SYBEUAVE,               1,	"Unable to allocate VMS event flag."},
{        SYBEUCPT,          EXUSER,	"Unrecognized custom-format parameter-type encountered in dbstrbuild()."},
{        SYBEUCRR,   EXCONSISTENCY,	"Internal software error: Unknown connection result reported by dbpasswd()."},
{        SYBEUDTY,   EXCONSISTENCY,	"Unknown datatype encountered."},
{        SYBEUFDS,          EXUSER,	"Unrecognized format encountered in dbstrbuild()."},
{        SYBEUFDT,   EXCONSISTENCY,	"Unknown fixed-length datatype encountered."},
{        SYBEUHST,          EXUSER,	"Unknown host machine name."},
{        SYBEUMSG,          EXCOMM,	"Unknown message-id in MSG datastream."},
{        SYBEUNAM,         EXFATAL,	"Unable to get current username from operating system."},
{        SYBEUNOP,      EXNONFATAL,	"Unknown option passed to dbsetopt()."},
{         SYBEUNT,          EXUSER,	"Unknown network type found in interface file."},
{        SYBEURCI,      EXRESOURCE,	"Unable to read copyright information from the dblib localization file."},
{        SYBEUREI,      EXRESOURCE,	"Unable to read error information from the dblib localization file."},
{        SYBEUREM,      EXRESOURCE,	"Unable to read error mnemonic from the dblib localization file."},
{        SYBEURES,      EXRESOURCE,	"Unable to read error string from the dblib localization file."},
{        SYBEURMI,      EXRESOURCE,	"Unable to read money-format information from the dblib localization file."},
{        SYBEUSCT,          EXCOMM,	"Unable to set communications timer."},
{        SYBEUTDS,          EXCOMM,	"Unrecognized TDS version received from SQL Server."},
{        SYBEUVBF,       EXPROGRAM,	"Attempt to read an unknown version of BCP format-file."},
{        SYBEUVDT,   EXCONSISTENCY,	"Unknown variable-length datatype encountered."},
{        SYBEVDPT,          EXUSER,	"For bulk copy, all variable-length data must have either a length-prefix or a terminator specified."},
{         SYBEVMS,               1,	"Sendflush: VMS IO error."},
{     SYBEVOIDRET,               1,	"Parameter of type SYBVOID cannot  be a return parameter."},
{        SYBEWAID,   EXCONSISTENCY,	"DB-LIBRARY internal error: ALTFMT following ALTNAME has wrong id."},
{        SYBEWRIT,          EXCOMM,	"Write to SQL Server failed."},
{        SYBEXOCI,      EXNONFATAL,	"A character-set translation overflowed its destination buffer while using bcp to copy data from a host-file to the SQL Server."},
{        SYBEXTDN,       EXPROGRAM,	"Warning:  the xlt_todisp parameter to dbfree_xlate() was NULL.  The space associated with the xlt_tosrv parameter has been freed."},
{         SYBEXTN,       EXPROGRAM,	"The xlt_todisp and xlt_tosrv parameters to dbfree_xlate() were NULL."},
{        SYBEXTSN,       EXPROGRAM,	"Warning:  the xlt_tosrv parameter to dbfree_xlate() was NULL.  The space associated with the xlt_todisp parameter has been freed."},
{        SYBEZTXT,          EXINFO,	"Attempt to send zero length TEXT or  IMAGE to dataserver via dbwritetext()."},
{               0,               0,	"Please add a description for this error to src/tds/error_table.h ($Id: error_table.h,v 1.3 2003-12-22 08:32:14 freddy77 Exp $)"}
