/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_exobel_routerkeygen_algorithms_ThomsonKeygen */

#ifndef _Included_org_exobel_routerkeygen_algorithms_ThomsonKeygen
#define _Included_org_exobel_routerkeygen_algorithms_ThomsonKeygen
#ifdef __cplusplus
extern "C" {
#endif
#undef org_exobel_routerkeygen_algorithms_ThomsonKeygen_MIN_PRIORITY
#define org_exobel_routerkeygen_algorithms_ThomsonKeygen_MIN_PRIORITY 1L
#undef org_exobel_routerkeygen_algorithms_ThomsonKeygen_NORM_PRIORITY
#define org_exobel_routerkeygen_algorithms_ThomsonKeygen_NORM_PRIORITY 5L
#undef org_exobel_routerkeygen_algorithms_ThomsonKeygen_MAX_PRIORITY
#define org_exobel_routerkeygen_algorithms_ThomsonKeygen_MAX_PRIORITY 10L
/*
 * Class:     org_exobel_routerkeygen_algorithms_ThomsonKeygen
 * Method:    thirdDicNative
 * Signature: ([B[B)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_exobel_routerkeygen_algorithms_ThomsonKeygen_thirdDicNative
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);


#ifdef __cplusplus
}
#endif
#endif
