#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_READLINE_READLINE_H 1
#define HAVE_READLINE_HISTORY_H 1
#define HAVE_RL_GETC 1
#define HAVE_RL_GETC_FUNCTION 1
#define HAVE_RL_FILENAME_COMPLETION_FUNCTION 1
#define HAVE_RL_USERNAME_COMPLETION_FUNCTION 1
#define HAVE_RL_COMPLETION_MATCHES 1
#define HAVE_RL_REFRESH_LINE 1
#define HAVE_RL_DEPREP_TERM_FUNCTION 1
#define HAVE_RL_COMPLETION_APPEND_CHARACTER 1
#define HAVE_RL_BASIC_WORD_BREAK_CHARACTERS 1
#define HAVE_RL_COMPLETER_WORD_BREAK_CHARACTERS 1
#define HAVE_RL_BASIC_QUOTE_CHARACTERS 1
#define HAVE_RL_COMPLETER_QUOTE_CHARACTERS 1
#define HAVE_RL_FILENAME_QUOTE_CHARACTERS 1
#define HAVE_RL_ATTEMPTED_COMPLETION_OVER 1
#define HAVE_RL_LIBRARY_VERSION 1
#define HAVE_RL_EDITING_MODE 1
#define HAVE_RL_LINE_BUFFER 1
#define HAVE_RL_POINT 1
#define HAVE_RL_EVENT_HOOK 1
#define HAVE_RL_CATCH_SIGWINCH 1
#define HAVE_RL_CATCH_SIGNALS 1
#define HAVE_RL_CLEANUP_AFTER_SIGNAL 1
#define HAVE_RL_FREE_LINE_STATE 1
#define HAVE_RL_CLEAR_SIGNALS 1
#define HAVE_RL_SET_SCREEN_SIZE 1
#define HAVE_RL_GET_SCREEN_SIZE 1
#define HAVE_RL_VI_EDITING_MODE 1
#define HAVE_RL_EMACS_EDITING_MODE 1
#define HAVE_REPLACE_HISTORY_ENTRY 1
#define HAVE_REMOVE_HISTORY 1
#define HAVE_CLEAR_HISTORY 1
#endif
