.\" Written by Domenico Andreoli for Debian GNU/Linux.
.\" Do whatever you want with this file.
.\" NO warranty is provided.
.TH libnet-config 1 "18 November 2002" "Libnet 1.1.0" "libnet-config manual"
.SH NAME
libnet-config \- Get information about a libnet installation
.SH SYNOPSIS
.B libnet-config [options]
.SH DESCRIPTION
.B libnet-config
displays information about a previous libnet installation.
.SH OPTIONS
.IP "--cflags"
Set of compiler options (CFLAGS) to use when compiling files that use
libnet.
.IP "--libs"
Shows the complete set of libs and other linker options you will need in order
to link your application with libnet.
.IP "--defines"
Set of compiler defines used to compile libnet.
.SH "EXAMPLES"
What linker options do I need when I link with libnet?

  libnet-config \-\-libs

What compiler options do I need when I compile using libnet functions?

  libnet-config \-\-cflags
.SH SEE ALSO
.BR libnet (3)
.SH AUTHOR
This manual page was written by Domenico Andreoli <cavok@debian.org>
for the Debian GNU/Linux system (but may be used by others).
