si.MyAppName=Firebird Database Server %1
si.ServerInstall=Polna instalacija serverja in razvojnih orodij.
si.SuperServerInstall=Polna instalacija super serverja in razvojnih orodij.
si.ClassicServerInstall=Polna instalacija klasiènega serverja in razvojnih orodij.
si.DeveloperInstall=Instalacija klientovih orodij za razvijalce in administratorje baze.
si.ClientInstall=Minimalna instalacija klienta - brez serverja, brez orodij.
si.CustomInstall=Prikrojena instalacija
si.SuperServerComponent=Super server
si.ClassicServerComponent=Klasièni server
si.ServerComponent=Komponente serverja
si.DevAdminComponent=Orodja za razvoj in administracijo
si.ClientComponent=Klientova orodja
si.UseGuardianTask=Ali uporabim &Guardian za nadzornika serverja?
si.UseApplicationTaskMsg=Zaženi server kot &aplikacijo?
si.TaskGroupDescription=Zaženi server kot:
si.UseServiceTask=Zaženi kot &servis?
si.AutoStartTask=Ali zaženem &Firebird server ob vsakem zagonu raèunalnika?
si.SuperClassicTask="Use SuperClassic?"
si.CopyFbClientToSysTask=Kopiraj &Firebird klientovo knjižnico v direktorij <system>?
si.CopyFbClientAsGds32Task=Ali izdelam klientovo knjižnico kot GDS32.DLL za podporo obstojeèim &aplikacijam?
si.InstallCPLAppletTask="Ali instaliram Control &Panel Applet?"
si.instreg=Vpisujem v Registry
si.instclientCopyFbClient=Kopiram fbclient v direktorij <sys>
si.instclientGenGds32=Izdelujem gds32.dll za direktorij <sys>
si.instclientDecLibCountGds32="Zmanjšujem števec uporabe deljene knjižnice za gds32 in jo brišem."
si.instclientDecLibCountFbClient="Zmanjšujem števec uporabe deljene knjižnice za fbclient in jo brišem."
si.instsvcSetup=Nastavite servisa
si.instsvcStartQuestion=Ali zaženem Firebird servis?
si.instsvcStartMsg=Zaganjam server
si.instsvcStopMsg="Ustavljam servis"
si.instsvcRemove="Odstranjuje servis"
si.instappStartQuestion=Ali seddaj zaženem Firebird?
si.instappStartMsg=Zaganjam server

si.InstallSummarySuffix1=Ta verzija Firebird bo postala uradna instalacija.
si.InstallSummarySuffix2=Prav tako velja, da lahko istalacija te verzije Firebirda,
si.InstallSummarySuffix3=v primeru, da je naslednja verzija programa že instalirana na
si.InstallSummarySuffix4=raèunalnik, nepredvidljivo vpliva na Firebird.

si.InstallSummaryCancel1= Èe boste nadaljevali z instalacijo Firebird serverja, bo ta instaliran ne pa tudi konfiguriran.
si.InstallSummaryCancel2= Instalacijo boste morali dopolniti roèno.
si.InstallSummaryCancel3= Ali želite prekiniti instalacijo?

si.InstalledProducts='pri ponovni instalaciji je bila najdena obstojeèa %s Firebird or Interbase %s been found.
si.InstalledProdCountSingular=verzija ima
si.InstalledProdCountPlural=verzije imajo

si.FbRunning1=Obstojeèa verzija Firebird %s Server je zagnana.
si.FbRunning2=Zaprite vse aplikacije oz. jih zakljuèite v
si.FbRunning3=nastavitah servisov.

si.PreviousInstallBroken=   (Instalacije je bila prekinjena zaradi neujemanja informacije o verzijah.)
si.PreviousInstallGood=   (Instalacije je uspela.)

si.IconReadme=Firebird %1 Readme
si.IconUninstall=Deinstalacija Firebird %1 serverja
si.ReleaseNotes= informacija o izdaji. (Potreben je programAcrobat Reader.)
si.InstallationGuide= installation guide. (Potreben je programAcrobat Reader.)
si.BugFixes= bug fixes. (Potreben je programAcrobat Reader.)
si.Uninstall=Deinstalacija Firebird %1
si.Winsock2Web1=Winsock 2 komponente niso instalirane.
si.Winsock2Web2=Ali želite obiskati domaèo stran za Winsock 2 posodobitev?
si.NoWinsock2 = Pred nadaljevanjem instalirajte Winsock 2 posodobitev
si.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

si.RunCSNoGuardian=Zaženi Firebird kot klasièni server (brez nadzornika)
si.RunSSNoGuardian=Zaženi Firebird kot super server (brez nadzornika)
si.RunSSWithGuardian=Zaženi Firebird kot super server (z nadzornikom)
si.RunCSWithGuardian=Zaženi Firebird kot klasièni server (z nadzornikom)
si.RunISQL=Zaženi ukazno vrstico z orodjem Interactive SQL
si.ReadmeFile=readme.txt
si.InstallationReadmeFile=instalacija_precitajMe.txt

si.RunCS=Zaženi Firebird kot klasièni server 
si.RunSC=Zaženi Firebird kot super klasièni server 
si.RunSS=Zaženi Firebird kot super server 

