it.MyAppName=Firebird Database Server %1
it.ServerInstall=Installazione completa di Server e strumenti di sviluppo.
it.SuperServerInstall=Installazione completa di Super Server e strumenti di sviluppo.
it.ClassicServerInstall=Installazione completa di Classic Server e strumenti di sviluppo.
it.DeveloperInstall=Installazione di strumenti lato client per amministrazione e sviluppo.
it.ClientInstall=Installazione client minima - senza server e senza strumenti.
it.CustomInstall=Installazione personalizzata
it.SuperServerComponent=File principali di Super Server
it.ClassicServerComponent=File principali di Classic Server
it.ServerComponent=Componenti Server
it.DevAdminComponent=Componenti per amministrazione e sviluppo
it.ClientComponent=Componenti client
it.UseGuardianTask=Usa il &Guardian per controllare il server?
it.UseApplicationTaskMsg=Esegui come &applicazione?
it.TaskGroupDescription=Esegui il server Firebird come:
it.UseServiceTask=Esegui come &servizio?
it.AutoStartTask=Esegui &Firebird automaticamente all'avvio del sistema?
it.SuperClassicTask="Use SuperClassic?"
it.CopyFbClientToSysTask=Copia la libreria client di &Firebird nella cartella di sistema?
it.CopyFbClientAsGds32Task=Usa il nome &GDS32.DLL per la libreria client, per compatibilità con precedenti versioni?
it.InstallCPLAppletTask="Installa il &Pannello di controllo di Firebird?"
it.instreg=Aggiornamento del registro di configurazione in corso
it.instclientCopyFbClient=Copia del file fbclient.dll nella cartella di sistema in corso
it.instclientGenGds32=Creazione del file gds32.dll nella cartella di sistema in corso
it.instclientDecLibCountGds32="Eliminazione del riferimento alla libreria condivisa gds32.dll in corso."
it.instclientDecLibCountFbClient="Eliminazione del riferimento alla libreria condivisa fbclient.dll in corso."
it.instsvcSetup=Installazione del servizio in corso
it.instsvcStartQuestion=Esegui il servizio Firebird ora?
it.instsvcStartMsg=Avvio del servizio Firebird in corso
it.instsvcStopMsg="Arresto del servizio in corso"
it.instsvcRemove="Disinstallazione del servizio in corso"
it.instappStartQuestion=Esegui Firebird ora?
it.instappStartMsg=Avvio del server Firebird in corso

it.InstallSummarySuffix1=Questa versione di Firebird diverrà l'istanza predefinita nel sistema.
it.InstallSummarySuffix2=    Attenzione: se si installa questa versione di Firebird su
it.InstallSummarySuffix3=    un sistema che ne contiene già una precedente, potrebbero
it.InstallSummarySuffix4=             verificarsi effetti imprevedibili.

it.InstallSummaryCancel1= Se si procede con l'installazione, Firebird verrà installato ma non configurato.
it.InstallSummaryCancel2= La configurazione dovrà essere effettuata manualmente.
it.InstallSummaryCancel3= Si desidera ANNULLARE l'installazione?

it.InstalledProducts=L'analisi preliminare ha evidenziato la presenza di %s %s di Firebird o InterBase.
it.InstalledProdCountSingular=versione
it.InstalledProdCountPlural=versioni

it.FbRunning1=Risulta al momento in esecuzione un'istanza di Firebird %s Server.
it.FbRunning2=     È necessario arrestare l'applicazione o il servizio
it.FbRunning3=                    prima di continuare.

it.PreviousInstallBroken=   (Installazione apparentemente danneggiata - mancata corrispondenza dei numeri di versione.)
it.PreviousInstallGood=   (Installazione corretta.)

it.IconReadme=Firebird %1 Leggimi
it.IconUninstall=Disinstallazione di Firebird %1
it.ReleaseNotes= note sul rilascio. (Richiede Acrobat Reader.)
it.InstallationGuide= installation guide. (Richiede Acrobat Reader.)
it.BugFixes= bug fixes. (Richiede Acrobat Reader.)
it.Uninstall=Disinstallazione di Firebird %1
it.Winsock2Web1=Winsock 2 non risulta installato.
it.Winsock2Web2=Si prega di visitare il sito di aggiornamento relativo a Winsock 2
it.NoWinsock2 = È necessario installare Winsock 2 prima di proseguire
it.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

it.RunCSNoGuardian=Esegui Firebird Classic Server (senza Guardian)
it.RunSSNoGuardian=Esegui Firebird Super Server (senza Guardian)
it.RunSSWithGuardian=Esegui Firebird Classic Server (con Guardian)
it.RunCSWithGuardian=Esegui Firebird Classic Server (con Guardian)
it.RunISQL=Esegui Interactive SQL (ISQL) da riga di comando

it.ReadmeFile=leggimi.txt
it.InstallationReadmeFile=leggimi_installazione.txt

it.RunCS=Esegui Firebird Classic server
it.RunSC=Esegui Firebird SuperClassic server
it.RunSS=Esegui Firebird SuperServer

