fr.MyAppName=Firebird Serveur SQL %1
fr.ServerInstall=Installation complète Serveur et outils de dévelopement.
fr.SuperServerInstall=Installation complète Super Serveur et outils de dévelopement.
fr.ClassicServerInstall=Installation complète Serveur Classique et outils de dévelopement.
fr.DeveloperInstall=Installation des outils Client pour Développeurs et administrateurs.
fr.ClientInstall=Installation client minimum - pas de serveur, pas d'outils.
fr.CustomInstall=Installation personnalisée
fr.SuperServerComponent=Binaires Super Serveur
fr.ClassicServerComponent=Binaires Serveur Classique
fr.ServerComponent=Composants serveur
fr.DevAdminComponent=Composants outils développeur et administrateur
fr.ClientComponent=Composants client
fr.UseGuardianTask=Utiliser &Guardian pour controler le serveur?
fr.UseApplicationTaskMsg=Exécuter en tant qu' &Application?
fr.TaskGroupDescription=Exécuter le serveur Firebird en tant que:
fr.UseServiceTask=Exécuter en tant que &Service?
fr.AutoStartTask=Exécuter automatiquement &Firebird à chaque démarrage?
fr.SuperClassicTask="Use SuperClassic?"
fr.CopyFbClientToSysTask=Copier la bibliothèque client &Firebird dans le répertoire <system>?
fr.CopyFbClientAsGds32Task=Générer la bibliothèque GDS32.DLL pour les anciennes app&lications?
fr.InstallCPLAppletTask="Installer l'application du panneau de configuration?"
fr.instreg=Mise à jour de la base de registre
fr.instclientCopyFbClient=Copie fbclient dans le répertoire <sys>
fr.instclientGenGds32=Génère gds32.dll pour le répertoire <sys>
fr.instclientDecLibCountGds32="Décrémente le compteur de gds32 et l'enlève si nécessaire."
fr.instclientDecLibCountFbClient="Décrémente le compteur de fbclient et l'enlève si nécessaire."
fr.instsvcSetup=Met en place le service
fr.instsvcStartQuestion=Démarrer le service Firebird?
fr.instsvcStartMsg=Démarre le service
fr.instsvcStopMsg="Arrête le service"
fr.instsvcRemove="Enlève le service"
fr.instappStartQuestion=Démarrer Firebird?
fr.instappStartMsg=Démarre le serveur

fr.InstallSummarySuffix1=Cette version de Firebird va devenir l'installation par défaut.
fr.InstallSummarySuffix2=   Aussi, notez bien qu'installer cette version de Firebird
fr.InstallSummarySuffix3=   quand une version plus ancienne est déjà installée peut
fr.InstallSummarySuffix4=          donner des résultats imprévisibles.

fr.InstallSummaryCancel1= Si vous continuez avec cette installation, Firebird sera installé mais pas configuré.
fr.InstallSummaryCancel2= Vous aurez à finir l''installation manuellement.
fr.InstallSummaryCancel3= Voulez-vous ANNULER cette installation?

fr.InstalledProducts=Selon l'analyse de pré-installation il existe %s installation(s) de Firebird ou Interbase%s.
;these are intentionally blank
fr.InstalledProdCountSingular=
fr.InstalledProdCountPlural=

fr.FbRunning1=Une version de Firebird %s Serveur est active.
fr.FbRunning2=   Vous devez fermer l'application ou arréter
fr.FbRunning3=           le service pour continuer.

fr.PreviousInstallBroken=   (L'installation semble être cassée à cause d'une disparité de la chaîne de version.)
fr.PreviousInstallGood=   (L'installation semble être bonne.)

fr.IconReadme=Firebird %1 Lisez Moi
fr.IconUninstall=Désinstaller Firebird %1
fr.ReleaseNotes= notes de version. (Nécessite Acrobat Reader.)
fr.InstallationGuide= guide d'installation. (Nécessite Acrobat Reader.)
fr.BugFixes= bug fixes. (Nécessite Acrobat Reader.)
fr.Uninstall=Désinstaller Firebird %1
fr.Winsock2Web1=Winsock 2 n'est pas installé.
fr.Winsock2Web2=Voulez-vous visiter la page web de mise à jour de Winsock 2 ?
fr.NoWinsock2 = S'il vous plait installez la mise à jour de Winsock 2 pour continuer
fr.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

fr.RunCSNoGuardian=Démarrer Firebird classic server (sans guardian)
fr.RunSSNoGuardian=Démarrer Firebird Superserver (sans guardian)
fr.RunSSWithGuardian=Démarrer Firebird Super Server (avec guardian)
fr.RunCSWithGuardian=Démarrer Firebird Classic Server (avec guardian)
fr.RunISQL=Démarrer l'outil en ligne de commande Interactive SQL (ISQL)

fr.ReadmeFile=lisezmoi.txt
fr.InstallationReadmeFile=installation_lisezmoi.txt
fr.IncompleteTranslationNotice=Ce document est une traduction et malgré nos efforts,il peut ne pas correspondre exactement à la dernière version, seul le texte original en anglais est toujours à jour.
fr.RunCS=Démarrer Firebird Classic server
fr.RunSC=Démarrer Firebird SuperClassic server
fr.RunSS=Démarrer Firebird SuperServer

