
#ifndef INCLUDE_gds
#define INCLUDE_gds

/*
 * Module: gds.h
 *
 * This file comes in two forms this one which is used in the
 * build tree and does a #include of all components and the
 * generated one used for external compilation which contains
 * a concatination of all the following files.
 *
 * The content of this file was generated by the Firebird project
 * and is a concatination of several header source files, that may
 * also explain the unusual #ifdef structures within this file.
 * 
 * 
 */


#include "../jrd/y_ref.h"
#include "../jrd/ibase.h"
#include "../jrd/gdsold.h"

#ifdef NOT_USED_OR_REPLACED

/* The public version of this file also contains the following header files
   these are not included explicitly here as they are included in the two 
   above files.  They have been placed here as a reminder of what is in
   the public version of this file.
*/
#include "fb_types.h"
#include "../jrd/blr.h"
#include "../include/gen/iberror.h"
#include "../include/gen/codes.h"
#endif

#endif /* INCLUDE_gds */

