#!perl

printf qq(/* %s */\n), '($Id: tds_willconvert.pl,v 1.3 2009-01-03 15:26:09 jklowden Exp $)';
printf qq(/*** %-67s ***/\n), "Please do not edit this file!";
printf qq(/*** %-67s ***/\n), "It was generated with 'perl tds_willconvert.pl > tds_willconvert.h'";
printf qq(/*** %-67s ***/\n), "It is much easier to edit the __DATA__ table than this file.  ";
printf qq(/*** %-67s ***/\n), " ";
printf qq(/*** %67s ***/\n\n), "Thank you.";

%yn = 	( T => 1
	, t => 0	# should be true, but not yet implemented.
	, F => 0
	);

$indent = "\t ";

sub category($) {
	$_ = shift;
	return qw(INT1 UINT1 INT2 UINT2 INT4 UINT4 INT8 UINT8) if $_ eq 'INTx';
	return qw(MONEY MONEY4) if $_ eq 'MONEYx';
	return qw(FLT8 REAL) if $_ eq 'FLTx';
	return qw(DATETIME DATETIME4) if $_ eq 'DATETIMEx';
	return $_;
}

while(<DATA>) {
	next if /^\s+To\s*$/;
	next if /^From/;
	if( /^\s+VARCHAR CHAR/ ) {
		@to = split;
		next;
	}
	last if /^\s*$/;

	@yn = split;
	$from = shift @yn;
	foreach $from (category($from)) {
		$i = 0;
		foreach $to (@to) {
			foreach $to (category($to)) {
				printf "$indent %-35s, %s }\n", "{ SYB${from}, SYB${to}", $yn{$yn[$i]};
			}
			++$i;
			$indent = "\t,";
		}
	}
}

__DATA__
          To
From
          VARCHAR CHAR TEXT BINARY VARBINARY IMAGE INTx FLTx NUMERIC DECIMAL BIT MONEYx DATETIMEx BOUNDARY UNIQUE SENSITIVITY
VARCHAR     T      T   T    T      T         T     T    T    T       T       T   T      T         T        T      t
CHAR        T      T   T    T      T         T     T    T    T       T       T   T      T         T        T      t
TEXT        T      T   T    T      T         T     T    T    T       T       T   T      T         T        T      t
BINARY      T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
VARBINARY   T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
IMAGE       T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
INTx        T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
FLTx        T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
NUMERIC     T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
DECIMAL     T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
BIT         T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
MONEYx      T      T   T    T      T         T     T    T    T       T       T   T      F         F        F      F
DATETIMEx   T      T   T    T      T         T     F    F    F       F       F   F      T         F        F      F
BOUNDARY    T      T   T    F      F         F     F    F    F       F       F   F      F         T        F      F
UNIQUE      T      T   T    F      F         F     F    F    F       F       F   F      F         F        T      F
SENSITIVITY t      t   t    F      F         F     F    F    F       F       F   F      F         F        F      t
