LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_CFLAGS:= 	-DPACKAGE_NAME="sqlite" -DPACKAGE_TARNAME="sqlite"\
				-DPACKAGE_VERSION="3.8.1" -DPACKAGE_STRING="sqlite 3.8.1"\
				-DPACKAGE_BUGREPORT="http://www.sqlite.org" -DPACKAGE_URL=""\
				-DPACKAGE="sqlite" -DVERSION="3.8.1" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1\
				-DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1\
				-DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1\
				-DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1\
				-DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1\
				-DHAVE_STRERROR_R=1 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1\
				-DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE

LOCAL_CXXFLAGS:=-Wall -fexceptions

LOCAL_C_INCLUDES:=	sqlite3

LOCAL_SRC_FILES:= 	sqlite3.c
					
LOCAL_MODULE:= libsqlite3

include $(BUILD_STATIC_LIBRARY)