hu.MyAppName=Firebird Adatbázisszerver %1.
hu.ServerInstall=Szerver és a fejlesztõi eszközök teljes telepítése
hu.SuperServerInstall=Szuper Szerver és a fejlesztõi eszközök teljes telepítése
hu.ClassicServerInstall=Hagyományos Szerver és a fejlesztõi eszközök teljes telepítése
hu.DeveloperInstall=Kliens eszközök telepítése fejlesztõk és adatbázis adminisztrátorok részére
hu.ClientInstall=Minimális Kliens telepítés - Szerver és a fejlesztõi eszközök nélkül
hu.CustomInstall=Egyedi telepítés
hu.SuperServerComponent=Szuper Szerver környezet
hu.ClassicServerComponent=Hagyományos Szerver környezet
hu.ServerComponent=Szerver komponensek
hu.DevAdminComponent=Fejlesztõi és adminisztrációs eszközök
hu.ClientComponent=Kliens komponensek
hu.UseGuardianTask=&Guardian szolgáltatás használata a Firebird Adatbázisszerver irányításához
hu.UseApplicationTaskMsg=&Programként
hu.TaskGroupDescription=A Firebird Adatbázisszerver futtatása:
hu.UseServiceTask=&Szolgáltatásként
hu.AutoStartTask=A &Firebird Adatbázisszerver automatikus indítása minden rendszerindításkor
hu.SuperClassicTask="Use SuperClassic?"
hu.CopyFbClientToSysTask=Másodpéldány a &Firebird kliens könyvtárról a <system> mappába
hu.CopyFbClientAsGds32Task=Másodpéldány a kliens könyvtárból, az ö&rökölt programok támogatására (GDS32.DLL)
hu.InstallCPLAppletTask=Firebird &Vezérlõpult Program telepítése
hu.instreg=Regisztrációs bejegyzések frissítése.
hu.instclientCopyFbClient=Az FBCLIENT.DLL fájl másolása a <system> mappába.
hu.instclientGenGds32=A GDS32.DLL fájl létrehozása a <system> mappában.
hu.instclientDecLibCountGds32=A GDS32.DLL fájl megosztott könyvtár számlálójának csökkentése és a amennyiben lehetséges a fájl eltávolítása.
hu.instclientDecLibCountFbClient=Az FBCLIENT.DLL fájl megosztott könyvtár számlálójának csökkentése és a amennyiben lehetséges a fájl eltávolítása.
hu.instsvcSetup=Szolgáltatás beállítása
hu.instsvcStartQuestion=A Firebird szolgáltatás azonnali elindítása
hu.instsvcStartMsg=A Firebird Szerver szolgáltatás azonnali elindítása.
hu.instsvcStopMsg=A szolgáltatás leállítása.
hu.instsvcRemove=A szolgáltatás eltávolítása.
hu.instappStartQuestion=A Firebird Szerver azonnali elindítása
hu.instappStartMsg=A Firebird Szerver elindítása.

hu.InstallSummarySuffix1=A Firebird Adatbázisszerver ezen verziója lesz az alapértelmezett telepítés.
hu.InstallSummarySuffix2=Továbbá vegye figyelembe, hogy a Firebird ezen verziójának telepítése
hu.InstallSummarySuffix3= a már telepített késõbbi verziókra megjósolhatatlan
hu.InstallSummarySuffix4=                 következményekkel járhat.

hu.InstallSummaryCancel1= Ha folytatja, a Firebird Adatbázisszerver telepítésre kerül, de nem lesz beállítva.
hu.InstallSummaryCancel2= A telepítés tökéletesítését kézzel kell majd elvégeznie.
hu.InstallSummaryCancel3= MEGSZAKÍTJA ezt a telepítést?

hu.InstalledProducts=Az újratelepítési vizsgálat az mutatja, hogy %s létezõ Firebird vagy Interbase telepítés %s a számítógépen.
hu.InstalledProdCountSingular=található
hu.InstalledProdCountPlural=találhatóak

hu.FbRunning1=Egy létezõ Firebird Adatbázisszerver %s már fut.
hu.FbRunning2= A folytatás elõtt Önnek be kell zárnia a futó alkalmazást,
hu.FbRunning3=          vagy le kell állítani szolgáltatást.

hu.PreviousInstallBroken=   (A telepítés hibásnak tûnik a nem megfelelõ verzió-azonosító miatt.)
hu.PreviousInstallGood=   (A telepítés hibátlannak tûnik.)

hu.IconReadme=Firebird %1 - Olvass El
hu.IconUninstall=A Firebird eltávolítása %1
hu.ReleaseNotes= Firebird %1 - Újdonságok (Acrobat Reader programot igényel)
hu.InstallationGuide= telepítési segédlet. (Acrobat Reader programot igényel)
hu.BugFixes= hibajavítások. (Acrobat Reader programot igényel)
hu.Uninstall=A Firebird eltávolítása %1
hu.Winsock2Web1=A Winsock 2 kiterjesztés nincs telepítve.
hu.Winsock2Web2=Meg kívánja látogatni a Winsock 2 frissítés honlapját?
hu.NoWinsock2=Kérem telepítse a Winsock 2 frissítést, mielõtt folytatná!
hu.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

hu.RunCSNoGuardian=Hagyományos Szerver futtatása (Guardian nélkül)
hu.RunSSNoGuardian=Szuper Szerver futtatása (Guardian nélkül)
hu.RunSSWithGuardian=A Szuper Szerver futtatása (Guardian segítségével)
hu.RunCSWithGuardian=A Hagyományos Szerver futtatása (Guardian segítségével)
hu.RunISQL=A parancssoros Interaktív SQL eszköz futtatása

hu.ReadmeFile=olvass_el.txt
hu.InstallationReadmeFile=telepitesi_segedlet.txt

hu.RunCS=Hagyományos Szerver futtatása 
hu.RunSC=Szuper Hagyományos Szerver futtatása 
hu.RunSS=Szuper Szerver futtatása 

