ru.MyAppName=Сервер баз данных Firebird %1
ru.ServerInstall=Полная установка сервера и инструментов разработки
ru.SuperServerInstall=Полная установка SuperServer и инструментов разработки
ru.ClassicServerInstall=Полная установка Classic Server и инструментов разработки
ru.DeveloperInstall=Установка инструментария для разработчиков и администраторов баз данных
ru.ClientInstall=Минимальная клиентская установка (без сервера и инструментов)
ru.CustomInstall=Выборочная установка
ru.SuperServerComponent=Бинарные файлы SuperServer
ru.ClassicServerComponent=Бинарные файлы Classic Server
ru.ServerComponent=Компоненты сервера
ru.DevAdminComponent=Инструменты разработчика и администратора
ru.ClientComponent=Клиентские компоненты
ru.UseGuardianTask=&Использовать Guardian для управления сервером
ru.UseApplicationTaskMsg=Запускать в качестве &Приложения
ru.TaskGroupDescription=Способ запуска сервера Firebird:
ru.UseServiceTask=Запускать в качестве &Службы
ru.AutoStartTask=&Автоматически запускать Firebird при каждой загрузке
ru.SuperClassicTask="Использовать SuperClassic?"
ru.CopyFbClientToSysTask=&Копировать клиентскую библиотеку Firebird в каталог <system>
ru.CopyFbClientAsGds32Task=&Создать GDS32.DLL для поддержки унаследованных приложений
ru.InstallCPLAppletTask=&Установить Апплет Панели Управления
ru.instreg=Обновление реестра
ru.instclientCopyFbClient=Копирование fbclient.dll в системный каталог
ru.instclientGenGds32=Создание gds32.dll в системном каталоге
ru.instclientDecLibCountGds32="Уменьшаем счетчик для общей библиотеки gds32 и удаляем ее, если необходимо."
ru.instclientDecLibCountFbClient="Уменьшаем счетчик для общей библиотеки fbclient и удаляем ее, если необходимо."
ru.instsvcSetup=Установка службы
ru.instsvcStartQuestion=Запустить Службу Firebird?
ru.instsvcStartMsg=Запуск сервера
ru.instsvcStopMsg="Остановка службы "
ru.instsvcRemove="Удаление службы "
ru.instappStartQuestion=Запустить Firebird?
ru.instappStartMsg=Запуск сервера

ru.InstallSummarySuffix1=Данная версия Firebird выполнит установку по умолчанию.
ru.InstallSummarySuffix2=Обратите внимание, что установка данной версии Firebird в случае,
ru.InstallSummarySuffix3=если уже установлена более поздняя версия, может привести
ru.InstallSummarySuffix4=к непредсказуемым результатам.

ru.InstallSummaryCancel1=Если вы продолжите установку этой версии, Firebird будет установлен, но не будет сконфигурирован.
ru.InstallSummaryCancel2=Вы должны завершить установку вручную.
ru.InstallSummaryCancel3=Хотите ли вы ПРЕКРАТИТЬ установку?

ru.InstalledProducts=Предварительный анализ показывает, что найдено %s %s Firebird или InterBase.
ru.InstalledProdCountSingular=установленных версий
ru.InstalledProdCountPlural=установленных версий

ru.FbRunning1=Обнаружен запущенный сервер %s.
ru.FbRunning2=Вы должны закрыть приложение или остановить
ru.FbRunning3=службу прежде, чем продолжите.

ru.PreviousInstallBroken=   (Установка не удалась по причине несовпадения строки версии)
ru.PreviousInstallGood=   (Установка прошла корректно)

ru.IconReadme=Firebird %1 Readme
ru.IconUninstall=Деинсталляция Firebird %1
ru.ReleaseNotes= release notes. (Требуется Acrobat Reader.)
ru.InstallationGuide= installation guide. (Требуется Acrobat Reader.)
ru.BugFixes= bug fixes. (Требуется Acrobat Reader.)
ru.Uninstall=Деинсталляция Firebird %1
ru.Winsock2Web1=Не установлен Winsock 2.
ru.Winsock2Web2=Хотите ли вы посетить домашнюю страницу обновления Winsock 2?
ru.NoWinsock2=Пожалуйста, установите обновление Winsock 2 прежде, чем продолжить
ru.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

ru.RunCSNoGuardian=Запуск Firebird Classic Server (без Guardian)
ru.RunSSNoGuardian=Запуск Firebird SuperServer (без Guardian)
ru.RunSSWithGuardian=Запуск Firebird SuperServer (с Guardian)
ru.RunCSWithGuardian=Запуск Firebird Classic Server (с Guardian)
ru.RunISQL=Запуск утилиты Interactive SQL

ru.ReadmeFile=readme.txt
ru.InstallationReadmeFile=installation_readme.txt
ru.RunCS=Запуск Firebird Classic Server
ru.RunSC=Запуск Firebird SuperClassic Server
ru.RunSS=Запуск Firebird SuperServer 
;ru.IncompleteTranslationNotice=This document is not up-to-date. Please refer to the original english language version for the latest information.
