de.MyAppName=Firebird Datenbank Server %1
de.ServerInstall=Vollständige Installation des Server inkl. Entwicklungstools.
de.SuperServerInstall=Vollständige Installation des Super Server inkl. Entwicklungstools.
de.ClassicServerInstall=Vollständige Installation des Classic Server inkl. Entwicklungstools.
de.DeveloperInstall=Installation der Client Tools für Entwickler und Datenbank-Administratoren.
de.ClientInstall=Minimale Client Installation - kein Server, keine Tools.
de.CustomInstall=Benutzerdefinierte Installation
de.SuperServerComponent=Super Server Binärdateien
de.ClassicServerComponent=Classic Server Binärdateien
de.ServerComponent=Server Komponenten
de.DevAdminComponent=Komponenten für Entwickler und Administratoren
de.ClientComponent=Client Komponenten
de.UseGuardianTask=Den &Guardian zum Kontrollieren des Servers verwenden?
de.UseApplicationTaskMsg=Server als &Anwendung starten?
de.TaskGroupDescription=Firebird Server starten als:
de.UseServiceTask=Server als &Dienst starten?
de.AutoStartTask=&Firebird nach jedem Rechnerneustart automatisch starten?
de.SuperClassicTask="Use SuperClassic?"
de.CopyFbClientToSysTask=Die Firebird &Client-Bibliothek ins <system>-Verzeichnis kopieren?
de.CopyFbClientAsGds32Task=Die Client-Bibliothek als &GDS32.DLL ins <system>-Verzeichnis kopieren?
de.InstallCPLAppletTask="Installieren eines &Symbols im Infobereich der Taskleiste?"
de.instreg=Die Registry wird aktualisiert
de.instclientCopyFbClient=Kopiere fbclient in das <sys> Verzeichnis
de.instclientGenGds32=Erstelle gds32.dll für das <sys> Verzeichnis
de.instclientDecLibCountGds32="Verringert den Zähler von gemeinsam benutzten Bibliotheken von gds32 und entfernt die Bibliothek wenn angebracht."
de.instclientDecLibCountFbClient="Verringert den Zähler von gemeinsam benutzten Bibliotheken von fbclient und entfernt die Bibliothek wenn angebracht."
de.instsvcSetup=Der Dienst wird eingerichtet
de.instsvcStartQuestion=Firebird jetzt als Dienst starten?
de.instsvcStartMsg=Der Dienst wird gestartet
de.instsvcStopMsg="Der Dienst wird gestoppt"
de.instsvcRemove="Der Dienst wird entfernt"
de.instappStartQuestion=Firebird jetzt starten?
de.instappStartMsg=Der Server wird gestartet

de.InstallSummarySuffix1=Diese Firebird Version wird die Standard Installation.
de.InstallSummarySuffix2=Beachten Sie, dass die Installation dieser Version von Firebird
de.InstallSummarySuffix3= zu unvorhersehbaren Ergebnissen führen kann, wenn eine neuere
de.InstallSummarySuffix4=           Version bereits installiert ist.

de.InstallSummaryCancel1= Wenn sie mit dieser Installation fortfahren, wird Firebird installiert aber nicht konfiguriert.
de.InstallSummaryCancel2= Sie müssen die Installation manuell fertig stellen.
de.InstallSummaryCancel3= Möchten Sie diese Installation ABBRECHEN?

de.InstalledProducts=Die Neuinstallations-Analyse ergibt, dass %s existierende Firebird oder Interbase %s
de.InstalledProdCountSingular=Version gefunden wurde.
de.InstalledProdCountPlural=Versionen gefunden wurden.

de.FbRunning1=Ein existierender Firebird %s Server läuft.
de.FbRunning2= Sie müssen die Anwendung schließen oder den Dienst
de.FbRunning3=         beenden, bevor Sie fortfahren können.

de.PreviousInstallBroken=   (Die Installation scheint wegen eines Versionskonflikts fehlerhaft zu sein.)
de.PreviousInstallGood=   (Die Installation scheint korrekt sein.)

de.IconReadme=Firebird %1 Liesmich
de.IconUninstall=Firebird %1 Deinstallation
de.ReleaseNotes= Release Hinweise. (Benötigt Acrobat Reader.)
de.InstallationGuide= Installationsanleitung. (Benötigt Acrobat Reader.)
de.BugFixes= bug fixes. (Benötigt Acrobat Reader.)
de.Uninstall=Firebird %1 deinstallieren
de.Winsock2Web1=Winsock 2 ist nicht installiert.
de.Winsock2Web2=Möchten Sie die Winsock 2 Update Home Page besuchen?
de.NoWinsock2 = Bitte installieren Sie das Winsock 2 Update, bevor Sie fortfahren
de.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

de.RunCSNoGuardian=Firebird Classic Server starten (ohne Guardian)
de.RunSSNoGuardian=Firebird Super Server starten (ohne Guardian)
de.RunSSWithGuardian=Firebird Super Server starten (Mit Guardian)
de.RunCSWithGuardian=Firebird Classic Server starten (Mit Guardian)
de.RunISQL=Starten des Kommandozeilen-basierten interaktiven SQL Tools

de.ReadmeFile=liesmich.txt
de.InstallationReadmeFile=installation_liesmich.txt

de.RunCS=Firebird Classic server starten
de.RunSC=Firebird SuperClassic server starten
de.RunSS=Firebird SuperServer starten

