static const char create_table_sql[] = 
"CREATE TABLE all_types_bcp_unittest (\n"
"	  not_null_bit			bit NOT NULL\n"
"\n"
"	, not_null_char			char(10) NOT NULL\n"
"	, not_null_varchar		varchar(10) NOT NULL\n"
"\n"
"	, not_null_datetime		datetime NOT NULL\n"
"	, not_null_smalldatetime	smalldatetime NOT NULL\n"
"\n"
"	, not_null_money		money NOT NULL\n"
"	, not_null_smallmoney		smallmoney NOT NULL\n"
"\n"
"	, not_null_float		float NOT NULL\n"
"	, not_null_real			real NOT NULL\n"
"\n"
"	, not_null_decimal		decimal(5,2) NOT NULL\n"
"	, not_null_numeric		numeric(5,2) NOT NULL\n"
"\n"
"	, not_null_int			int NOT NULL\n"
"	, not_null_smallint		smallint NOT NULL\n"
"	, not_null_tinyint		tinyint NOT NULL\n"
"\n"
"	, nullable_char			char(10)  NULL\n"
"	, nullable_varchar		varchar(10)  NULL\n"
"\n"
"	, nullable_datetime		datetime  NULL\n"
"	, nullable_smalldatetime	smalldatetime  NULL\n"
"\n"
"	, nullable_money		money  NULL\n"
"	, nullable_smallmoney		smallmoney  NULL\n"
"\n"
"	, nullable_float		float  NULL\n"
"	, nullable_real			real  NULL\n"
"\n"
"	, nullable_decimal		decimal(5,2)  NULL\n"
"	, nullable_numeric		numeric(5,2)  NULL\n"
"\n"
"	, nullable_int			int  NULL\n"
"	, nullable_smallint		smallint  NULL\n"
"	, nullable_tinyint		tinyint  NULL\n"
"\n"
"	/* Excludes: \n"
"	 * binary\n"
"	 * image\n"
"	 * uniqueidentifier\n"
"	 * varbinary\n"
"	 * text\n"
"	 * timestamp\n"
"	 * nchar\n"
"	 * ntext\n"
"	 * nvarchar\n"
"	 */\n"
")\n"
"\n"
"INSERT all_types_bcp_unittest   \n"
"VALUES ( 1 -- not_null_bit\n"
"\n"
"	, 'a char' -- not_null_char\n"
"	, 'a varchar' -- not_null_varchar\n"
"\n"
"	, 'Dec 17 2003  3:44PM' -- not_null_datetime\n"
"	, 'Dec 17 2003  3:44PM' -- not_null_smalldatetime\n"
"\n"
"	, 12.34 -- not_null_money\n"
"	, 12.34 -- not_null_smallmoney\n"
"\n"
"	, 12.34 -- not_null_float\n"
"	, 12.34 -- not_null_real\n"
"\n"
"	, 12.34 -- not_null_decimal\n"
"	, 12.34 -- not_null_numeric\n"
"\n"
"	, 1234 -- not_null_int\n"
"	, 1234 -- not_null_smallint\n"
"	, 123  -- not_null_tinyint\n"
"\n"
"	, 'a char' -- nullable_char\n"
"	, 'a varchar' -- nullable_varchar\n"
"\n"
"	, 'Dec 17 2003  3:44PM' -- nullable_datetime\n"
"	, 'Dec 17 2003  3:44PM' -- nullable_smalldatetime\n"
"\n"
"	, 12.34 -- nullable_money\n"
"	, 12.34 -- nullable_smallmoney\n"
"\n"
"	, 12.34 -- nullable_float\n"
"	, 12.34 -- nullable_real\n"
"\n"
"	, 12.34 -- nullable_decimal\n"
"	, 12.34 -- nullable_numeric\n"
"\n"
"	, 1234 -- nullable_int\n"
"	, 1234 -- nullable_smallint\n"
"	, 123  -- nullable_tinyint\n"
")\n"
"INSERT all_types_bcp_unittest\n"
"				( not_null_bit			\n"
"\n"
"				, not_null_char			\n"
"				, not_null_varchar		\n"
"\n"
"				, not_null_datetime		\n"
"				, not_null_smalldatetime	\n"
"\n"
"				, not_null_money		\n"
"				, not_null_smallmoney		\n"
"\n"
"				, not_null_float		\n"
"				, not_null_real			\n"
"\n"
"				, not_null_decimal		\n"
"				, not_null_numeric		\n"
"\n"
"				, not_null_int			\n"
"				, not_null_smallint		\n"
"				, not_null_tinyint		\n"
"				) \n"
"VALUES (\n"
"	  1 -- not_null_bit\n"
"\n"
"	, 'a char' -- not_null_char\n"
"	, 'a varchar' -- not_null_varchar\n"
"\n"
"	, 'Dec 17 2003  3:44PM' -- not_null_datetime\n"
"	, 'Dec 17 2003  3:44PM' -- not_null_smalldatetime\n"
"\n"
"	, 12.34 -- not_null_money\n"
"	, 12.34 -- not_null_smallmoney\n"
"\n"
"	, 12.34 -- not_null_float\n"
"	, 12.34 -- not_null_real\n"
"\n"
"	, 12.34 -- not_null_decimal\n"
"	, 12.34 -- not_null_numeric\n"
"\n"
"	, 1234 -- not_null_int\n"
"	, 1234 -- not_null_smallint\n"
"	, 123  -- not_null_tinyint\n"
")\n";

