/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sleepycat.db.internal;

import com.sleepycat.db.*;
import java.util.Comparator;

public class DbChannel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DbChannel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DbChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* package */ synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

	public synchronized void close(int flags) throws DatabaseException {
		try {
			close0(flags);
		} finally {
			swigCPtr = 0;
		}
	}

  /* package */ void close0(int flags) { db_javaJNI.DbChannel_close0(swigCPtr, this, flags); }

  public void send_repmsg(com.sleepycat.db.DatabaseEntry[] chan_msgs, int nmsg, int flags) throws com.sleepycat.db.DatabaseException { db_javaJNI.DbChannel_send_repmsg(swigCPtr, this, chan_msgs, nmsg, flags); }

  public void send_request(com.sleepycat.db.DatabaseEntry[] chan_msgs, int nrequest, com.sleepycat.db.DatabaseEntry response, long timeout, int flags) throws com.sleepycat.db.DatabaseException { db_javaJNI.DbChannel_send_request(swigCPtr, this, chan_msgs, nrequest, response, timeout, flags); }

  public void set_timeout(long timeout) throws com.sleepycat.db.DatabaseException { db_javaJNI.DbChannel_set_timeout(swigCPtr, this, timeout); }

}
