LOCAL_PATH := $(call my-dir)
MY_LOCAL_PATH := $(LOCAL_PATH)
include $(CLEAR_VARS)

include $(MY_LOCAL_PATH)/thomson/Android.mk
include $(MY_LOCAL_PATH)/arpspoof/Android.mk
include $(MY_LOCAL_PATH)/libpcap/Android.mk
include $(MY_LOCAL_PATH)/libnet/Android.mk
include $(MY_LOCAL_PATH)/openssl/Android.mk
include $(MY_LOCAL_PATH)/tcpdump/Android.mk
include $(MY_LOCAL_PATH)/ettercap-ng/Android.mk
include $(MY_LOCAL_PATH)/sqlite/dist/Android.mk
include $(MY_LOCAL_PATH)/libmysqlclient/Android.mk
include $(MY_LOCAL_PATH)/postgresql/Android.mk
include $(MY_LOCAL_PATH)/apr/Android.mk
include $(MY_LOCAL_PATH)/apr-util/Android.mk
include $(MY_LOCAL_PATH)/subversion/Android.mk
include $(MY_LOCAL_PATH)/unixODBC/Android.mk
include $(MY_LOCAL_PATH)/libiconv/Android.mk
include $(MY_LOCAL_PATH)/libneon/Android.mk
include $(MY_LOCAL_PATH)/bdb/build_android/Android.mk
include $(MY_LOCAL_PATH)/libexpat/Android.mk
include $(MY_LOCAL_PATH)/libssh/Android.mk
include $(MY_LOCAL_PATH)/libreadline/Android.mk
include $(MY_LOCAL_PATH)/libpcre/Android.mk
include $(MY_LOCAL_PATH)/libncp/Android.mk
include $(MY_LOCAL_PATH)/libidn/Android.mk
include $(MY_LOCAL_PATH)/libtommath/Android.mk
include $(MY_LOCAL_PATH)/firebird/Android.mk
include $(MY_LOCAL_PATH)/hydra/Android.mk
include $(MY_LOCAL_PATH)/nmap/Android.mk
include $(MY_LOCAL_PATH)/libbthread/Android.mk
include $(MY_LOCAL_PATH)/ruby/Android.mk
include $(MY_LOCAL_PATH)/icu4c/Android.mk
include $(MY_LOCAL_PATH)/libxml2/Android.mk
include $(MY_LOCAL_PATH)/libxslt/Android.mk
include $(MY_LOCAL_PATH)/libyaml/Android.mk
include $(MY_LOCAL_PATH)/ncurses/Android.mk
include $(MY_LOCAL_PATH)/zlib/Android.mk
include $(MY_LOCAL_PATH)/libedit/Android.mk
include $(MY_LOCAL_PATH)/openldap/Android.mk
include $(MY_LOCAL_PATH)/freetds/Android.mk
include $(MY_LOCAL_PATH)/libifaddrs/Android.mk
include $(MY_LOCAL_PATH)/libcurl/Android.mk
include $(MY_LOCAL_PATH)/fusemounts/Android.mk
include $(MY_LOCAL_PATH)/cSploitCommon/Android.mk
include $(MY_LOCAL_PATH)/cSploitDaemon/Android.mk
include $(MY_LOCAL_PATH)/cSploitHandlers/Android.mk
include $(MY_LOCAL_PATH)/cSploitClient/Android.mk
include $(MY_LOCAL_PATH)/libcares/Android.mk
include $(MY_LOCAL_PATH)/known-issues/Android.mk
include $(MY_LOCAL_PATH)/network-radar/Android.mk
