#! /bin/sh
# $OpenLDAP$
## This work is part of OpenLDAP Software <http://www.openldap.org/>.
##
## Copyright 1998-2014 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

echo "### This test requires the ldap backend and glue overlay."
echo "### If available, and explicitly requested, it can use SASL bind;"
echo "### note that SASL must be properly set up, and the requested"
echo "### mechanism must be available.  Define SLAPD_USE_SASL={yes|<mech>},"
echo "### with \"yes\" defaulting to DIGEST-MD5 to enable SASL authc[/authz]."

if test $BACKLDAP = "ldapno" ; then 
	echo "LDAP backend not available, test skipped"
	exit 0
fi 

if test $WITH_SASL = "yes" ; then
	if test $USE_SASL != "no" ; then
		if test $USE_SASL = "yes" ; then
			MECH="DIGEST-MD5"
		else
			MECH="$USE_SASL"
		fi
		echo "Using SASL authc[/authz] with mech=$MECH; unset SLAPD_USE_SASL to disable"
	else
		echo "Using proxyAuthz with simple authc..."
	fi
else
	echo "SASL not available; using proxyAuthz with simple authc..."
fi

mkdir -p $TESTDIR $DBDIR1 $DBDIR2 $DBDIR3

echo "Running slapadd to build slapd database..."
. $CONFFILTER $BACKEND $MONITORDB < $LDAPGLUECONF1 > $ADDCONF
$SLAPADD -f $ADDCONF -l $LDIFLDAPGLUE1
RC=$?
if test $RC != 0 ; then
	echo "slapadd 1 failed ($RC)!"
	exit $RC
fi

. $CONFFILTER $BACKEND $MONITORDB < $LDAPGLUECONF2 > $ADDCONF
$SLAPADD -f $ADDCONF -l $LDIFLDAPGLUE2
RC=$?
if test $RC != 0 ; then
	echo "slapadd 2 failed ($RC)!"
	exit $RC
fi

. $CONFFILTER $BACKEND $MONITORDB < $LDAPGLUECONF3 > $ADDCONF
$SLAPADD -f $ADDCONF -l $LDIFLDAPGLUE3
RC=$?
if test $RC != 0 ; then
	echo "slapadd 3 failed ($RC)!"
	exit $RC
fi

echo "Starting local slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $LDAPGLUECONF1 > $CONF1
$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
PID1=$!
if test $WAIT != 0 ; then
    echo PID $PID1
    read foo
fi

echo "Starting remote slapd 1 on TCP/IP port $PORT2..."
. $CONFFILTER $BACKEND $MONITORDB < $LDAPGLUECONF2 > $CONF2
$SLAPD -f $CONF2 -h $URI2 -d $LVL $TIMING > $LOG2 2>&1 &
PID2=$!
if test $WAIT != 0 ; then
    echo PID $PID2
    read foo
fi

echo "Starting remote slapd 2 on TCP/IP port $PORT3..."
. $CONFFILTER $BACKEND $MONITORDB < $LDAPGLUECONF3 > $CONF3
$SLAPD -f $CONF3 -h $URI3 -d $LVL $TIMING > $LOG3 2>&1 &
PID3=$!
if test $WAIT != 0 ; then
    echo PID $PID3
    read foo
fi
KILLPIDS="$PID1 $PID2 $PID3"

sleep 1

echo "Using ldapsearch to check that slapd is running..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

echo "Using ldapsearch to check that slapd is running..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT2 \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

echo "Using ldapsearch to check that slapd is running..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT3 \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

ID="uid=bjorn,ou=People,dc=example,dc=com"
BASE="dc=example,dc=com"
echo "Testing ldapsearch as $ID for \"$BASE\"..."
$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASE" \
	-D "$ID" -w bjorn > $SEARCHOUT 2>&1

RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	test $KILLSERVERS != no && kill -HUP $KILLPIDS
	exit $RC
fi

echo "Filtering ldapsearch results..."
$LDIFFILTER -s ldif=e < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
$LDIFFILTER -s ldif=e < $LDAPGLUEOUT > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
	
if test $? != 0 ; then
	echo "comparison failed - glued search with identity assertion didn't succeed"
	test $KILLSERVERS != no && kill -HUP $KILLPIDS
	exit 1
fi

BASE="dc=example,dc=com"
echo "Testing ldapsearch as anonymous for \"$BASE\"..."
$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASE" \
	 > $SEARCHOUT 2>&1

RC=$?
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	test $KILLSERVERS != no && kill -HUP $KILLPIDS
	exit $RC
fi

echo "Filtering ldapsearch results..."
$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
$LDIFFILTER < $LDAPGLUEANONYMOUSOUT > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
	
if test $? != 0 ; then
	echo "comparison failed - anonymous glued search with identity assertion didn't succeed"
	test $KILLSERVERS != no && kill -HUP $KILLPIDS
	exit 1
fi

# FIXME: this cannot work as is, because SASL bind cannot be proxied!
if test $USE_SASL != "no" ; then
	ID="bjorn"
	BASE="dc=example,dc=com"
	echo "Testing ldapsearch as $ID for \"$BASE\" with SASL bind and identity assertion..."
	$LDAPSASLSEARCH -h $LOCALHOST -p $PORT1 -b "$BASE" \
		-Q -U "$ID" -w bjorn -Y $MECH > $SEARCHOUT 2>&1

	RC=$?
	if test $RC != 0 ; then
		echo "ldapsearch failed ($RC)!"
		test $KILLSERVERS != no && kill -HUP $KILLPIDS
		exit $RC
	fi

	echo "Filtering ldapsearch results..."
	$LDIFFILTER < $SEARCHOUT > $SEARCHFLT
	echo "Filtering original ldif used to create database..."
	$LDIFFILTER < $LDAPGLUEOUT > $LDIFFLT
	echo "Comparing filter output..."
	$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
	
	if test $? != 0 ; then
		echo "comparison failed - glued search with SASL bind and identity assertion didn't succeed"
		test $KILLSERVERS != no && kill -HUP $KILLPIDS
		exit 1
	fi
fi

test $KILLSERVERS != no && kill -HUP $KILLPIDS

echo ">>>>> Test succeeded"

test $KILLSERVERS != no && wait

exit 0
