#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_CONFIG_H 1
#define HAVE_SHA256_TRANSFORM 1
#define HAVE_SHA512_TRANSFORM 1
#define HAVE_TYPE_SHA256_CTX 1
#define HAVE_TYPE_SHA512_CTX 1
#define SHA2_USE_OPENSSL 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_TYPE_UINT64_T 1
#endif
