pl.MyAppName=Serwer bazy danych Firebird %1
pl.ServerInstall=Pe³na instalacja (Server) i narzêdzi programistycznych.
pl.SuperServerInstall=Pe³na instalacja (Super Server) i narzêdzi programistycznych.
pl.ClassicServerInstall=Pe³na instalacja (Classic Server) i narzêdzi programistycznych.
pl.DeveloperInstall=Instalacja narzêdzi klienta dla programistów i administratorów bazy danych.
pl.ClientInstall=Minimalna instalacja klienta - bez serwera i narzêdzi programistycznych.
pl.CustomInstall=Instalacja niestandardowa
pl.SuperServerComponent=Super Server - binaria
pl.ClassicServerComponent=Classic Server - binaria
pl.ServerComponent=Komponenty serwera
pl.DevAdminComponent=Narzêdzia programisty i administratora
pl.ClientComponent=Komponenty klienta
pl.UseGuardianTask=U¿ywanie &Guardian'a do kontrolowania serwera
pl.UseApplicationTaskMsg=&Aplikacja
pl.TaskGroupDescription=Uruchamienie Firebird'a jako:
pl.UseServiceTask=&Us³uga
pl.AutoStartTask=Uruchamianie &Firebird'a automatycznie przy ka¿dym starcie systemu
pl.SuperClassicTask="Use SuperClassic?"
pl.CopyFbClientToSysTask=Kopiowanie &biblioteki klienta Firebird katalogu <system>
pl.CopyFbClientAsGds32Task=Wygenerowanie biblioteki klienta jako GDS32.DLL do &obs³ugiwania starszych aplikacji
pl.InstallCPLAppletTask=Instalacja apletu w oknie &Panel sterowania
pl.instreg=Uaktualnienie rejestrów systemu
pl.instclientCopyFbClient=Kopiowanie fbclient do katalogu <sys>
pl.instclientGenGds32=Generowanie gds32.dll w katalogu <sys>
pl.instclientDecLibCountGds32=Zmniejszenie licznika biblioteki wspó³dzielonej gds32 i usuniêcie jej jeœli nie jest potrzebna.
pl.instclientDecLibCountFbClient=Zmniejszenie licznika biblioteki wspó³dzielonej fbclient i usuniêcie jej jeœli nie jest potrzebna.
pl.instsvcSetup=Konfigurowanie us³ugi
pl.instsvcStartQuestion=Czy uruchomiæ teraz us³ugê Firebird'a ?
pl.instsvcStartMsg=Uruchamianie serwera
pl.instsvcStopMsg=Zatrzymywanie us³ugi
pl.instsvcRemove=Usuwanie us³ugi
pl.instappStartQuestion=Czy uruchomiæ teraz Firebird'a ?
pl.instappStartMsg=Uruchamianie serwera

pl.InstallSummarySuffix1=Ta wersja Firebird'a stanie siê domyœln¹ instalacj¹.
pl.InstallSummarySuffix2=Zwróæmy uwagê na to, ¿e instalowanie tej wersji Firebird'a w momencie
pl.InstallSummarySuffix3= gdy jest ju¿ zainstalowana jego nowsza wersja, mo¿e doprowadziæ
pl.InstallSummarySuffix4=                 do nieprzewidzianych skutków.

pl.InstallSummaryCancel1= Jeœli bêdziesz kontynuowaæ tê instalacjê to Firebird zostanie zainstalowany, ale nie skonfigurowany.
pl.InstallSummaryCancel2= Bêdziesz musia³ dokoñczyæ instalacjê rêcznie.
pl.InstallSummaryCancel3= Czy chcesz PRZERWAÆ instalacjê ?

pl.InstalledProducts=Analiza przed instalacj¹ wykaza³a, ¿e ju¿ istnieje %s Firebird lub Interbase %s
pl.InstalledProdCountSingular=wersja posiada
pl.InstalledProdCountPlural=wersje posiadaj¹

pl.FbRunning1=Istniej¹cy Firebird %s Server jest uruchomiony.
pl.FbRunning2= Przed kontynuacj¹ musisz zakoñczyæ program
pl.FbRunning3=       lub zatrzymaæ us³ugê.

pl.PreviousInstallBroken=   (Instalacja wygl¹da na b³êdn¹, z powodu konfliktu wersji.)
pl.PreviousInstallGood=   (Instalacja wygl¹da na poprawn¹.)

pl.IconReadme=Firebird %1 - przeczytaj mnie
pl.IconUninstall=Deinstalacja Firebird'a %1
pl.ReleaseNotes= Informacje o wydaniu. (Wymagany Acrobat Reader.)
pl.InstallationGuide= installation guide. (Wymagany Acrobat Reader.)
pl.BugFixes= bug fixes. (Wymagany Acrobat Reader.)
pl.Uninstall=Deinstalacja Firebird'a %1
pl.Winsock2Web1=Winsock 2 nie jest zainstalowany.
pl.Winsock2Web2=Czy chcesz odwiedziæ stronê z aktualizacjami Winsock 2 ?
pl.NoWinsock2=Przed kontynuacj¹ nale¿y zainstalowaæ aktualizacjê Winsock 2
pl.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

pl.RunCSNoGuardian=Uruchom Firebird Classic Server (bez guardian'a)
pl.RunSSNoGuardian=Uruchom Firebird Superserver (bez guardian'a)
pl.RunSSWithGuardian=Urumom Firebird Super Server (z guardian'em)
pl.RunCSWithGuardian=Uruchom Firebird Classic Server (z guardian'em)
pl.RunISQL=Uruchom Interactive SQL - narzêdzie wiersza poleceñ

pl.ReadmeFile=czytajto.txt
pl.InstallationReadmeFile=instalacja_czytajto.txt

pl.RunCS=Uruchom Firebird Classic server
pl.RunSC=Uruchom Firebird SuperClassic server
pl.RunSS=Uruchom Firebird SuperServer

