ba.MyAppName=Firebird Database Server %1
ba.ServerInstall=Puna instalacija Server-a i razvojnih alata.
ba.SuperServerInstall=Puna instalacija Super Server-a i razvojnih alata.
ba.ClassicServerInstall=Puna instalacija Classic Server-a i razvojnih alata.
ba.DeveloperInstall=Instalacija Client alata za Developere i database administratore.
ba.ClientInstall=Minimalna instalacija client-a - bez server-a, bez alata.
ba.CustomInstall=Custom instalacija
ba.SuperServerComponent=Super Server
ba.ClassicServerComponent=Classic Server
ba.ServerComponent=Serverske komponente
ba.DevAdminComponent=Komponente za razvoj i administraciju
ba.ClientComponent=Client-ske komponente
ba.UseGuardianTask=Koristiti &Guardian za kontrolu server-a?
ba.UseApplicationTaskMsg=Pokreni kao &Application?
ba.TaskGroupDescription=Pokreni Firebird server kao:
ba.UseServiceTask=Pokreni kao &Service?
ba.AutoStartTask=Pokreni &Firebird automatski uvijek kad upalite raèunar?
ba.SuperClassicTask="Use SuperClassic?"
ba.CopyFbClientToSysTask=Kopiraj &Firebird client biblioteku (library) u folder <system>?
ba.CopyFbClientAsGds32Task=Generiši client biblioteku (library) kao GDS32.DLL za podršku starim-postojeæim (&legacy) programima?
ba.InstallCPLAppletTask="Instaliraj Control &Panel Applet?"
ba.instreg=Upisujem u registry
ba.instclientCopyFbClient=Kopiram fbclient u folder <sys>
ba.instclientGenGds32=Generišem gds32.dll u folder <sys>
ba.instclientDecLibCountGds32="Umanjujem brojaè upotrebe za biblioteku gds32 i uklanjam ako treba."
ba.instclientDecLibCountFbClient="Umanjujem brojaè upotrebe za biblioteku fbclient i uklanjam ako treba."
ba.instsvcSetup=Podešavam service
ba.instsvcStartQuestion=Pokreni Firebird Service sada?
ba.instsvcStartMsg=Pokreæem server
ba.instsvcStopMsg="Zaustavljam service"
ba.instsvcRemove="Uklanjam service"
ba.instappStartQuestion=Pokreni Firebird sada?
ba.instappStartMsg=Pokreæem server

ba.InstallSummarySuffix1=Ova verzija Firebird-a æe postati default install.
ba.InstallSummarySuffix2=Osim toga, obratite pažnju da instalacija ove verzije Firebird-a
ba.InstallSummarySuffix3= kada je sljedeæa verzija veæ instalirana može dovesti do
ba.InstallSummarySuffix4=                 nepredvidivih rezultata.

ba.InstallSummaryCancel1= Ako nastavite sa ovom instalacijom Firebird æe biti instaliran ali ne i konfigurisan.
ba.InstallSummaryCancel2= Moraæete da kompletirate instalaciju ruèno.
ba.InstallSummaryCancel3= Želite li da ODUSTANETE od ove instalacije?

ba.InstalledProducts='Pre-instalaciona analiza pokazuje da %s postojeæi Firebird ili Interbase %s je pronadjen.
ba.InstalledProdCountSingular=verzija ima
ba.InstalledProdCountPlural=verzije imaju

ba.FbRunning1=Postojeæi Firebird %s Server je pokrenut.
ba.FbRunning2= Morate zatvoriti aplikaciju ili zaustaviti
ba.FbRunning3=         service prije nastavka.

ba.PreviousInstallBroken=   (Instalacija je neuspješna zbog razlike u verzijama.)
ba.PreviousInstallGood=   (Instalacija je uspješna.)

ba.IconReadme=Firebird %1 Readme
ba.IconUninstall=Deinstalacija Firebird-a %1
ba.ReleaseNotes= release notes. (Potreban je Acrobat Reader.)
ba.InstallationGuide= installation guide. (Potreban je Acrobat Reader.)
ba.BugFixes= bug fixes. (Potreban je Acrobat Reader.)

ba.Uninstall=Deinstalacija Firebird-a %1
ba.Winsock2Web1=Winsock 2 nije instaliran.
ba.Winsock2Web2=Želite li da posjetite Winsock 2 Update Home Page?
ba.NoWinsock2 = Molimo instalirajte Winsock 2 Update prije nastavka
ba.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

ba.RunCSNoGuardian=Pokreni Firebird classic server (bez guardian-a)
ba.RunSSNoGuardian=Pokreni Firebird Superserver (bez guardian-a)
ba.RunSSWithGuardian=Pokreni Firebird Super Server (sa guardian-om)
ba.RunCSWithGuardian=Pokreni Firebird Classic Server (sa guardian-om)
ba.RunISQL=Pokreni command-line bazirani Interactive SQL alat

ba.ReadmeFile=ProcitajMe.txt
ba.InstallationReadmeFile=Instalacija_ProcitajMe.txt

ba.RunCS=Pokreni Firebird Classic server
ba.RunSC=Pokreni Firebird SuperClassic server
ba.RunSS=Pokreni Firebird SuperServer

