pt.MyAppName=Servidor SQL Firebird %1
pt.ServerInstall=Instalação completa do Server e ferramentas de desenvolvimento.
pt.SuperServerInstall=Instalação completa do Super Server e ferramentas de desenvolvimento.
pt.ClassicServerInstall=Instalação completa do Classic Server e ferramentas de desenvolvimento.
pt.DeveloperInstall=Instalação das ferramentas do Cliente para programadores e administradores.
pt.ClientInstall=Instalação mínima do Cliente - sem servidor, sem ferramentas.
pt.CustomInstall=Instalação personalizada.
pt.SuperServerComponent=Binários Super Server
pt.ClassicServerComponent=Binários Classic Server
pt.ServerComponent=Componentes do Servidor
pt.DevAdminComponent=Componentes do Programador e das ferramentas de administração
pt.ClientComponent=Componentes do Cliente
pt.UseGuardianTask=Usar o &Guardian para controlar o servidor?
pt.UseApplicationTaskMsg=Executar como &Aplicação?
pt.TaskGroupDescription=Executar o servidor Firebird como:
pt.UseServiceTask=Executar como um &Serviço?
pt.AutoStartTask=Iniciar o &Firebird automaticamente de cada vez que o sistema arranca?
pt.SuperClassicTask="Usar SuperClassic?"
pt.CopyFbClientToSysTask=Copiar a biblioteca do cliente &Firebird para a pasta de <system>?
pt.CopyFbClientAsGds32Task=Criar a biblioteca cliente como GDS32.DLL para "retro-compatibilidade"?
pt.InstallCPLAppletTask="Instalar a aplicação do &Painel de Controlo?"
pt.instreg=A atualizar o registo
pt.instclientCopyFbClient=A copiar o fbclient para a pasta <sys>
pt.instclientGenGds32=A criar o gds32.dll na pasta <sys>
pt.instclientDecLibCountGds32="A decrementar o contador de bibliotecas partilhadas para o gds32 e a removê-lo se possível."
pt.instclientDecLibCountFbClient="A decrementar o contador de bibliotecas partilhadas para o fbclient e a removê-lo se possível."
pt.instsvcSetup=A configurar o serviço
pt.instsvcStartQuestion=Iniciar o Serviço Firebird agora?
pt.instsvcStartMsg=A iniciar o servidor
pt.instsvcStopMsg="A parar o servidor"
pt.instsvcRemove="A remover o servidor"
pt.instappStartQuestion=Iniciar o Firebird agora?
pt.instappStartMsg=A iniciar o servidor

pt.InstallSummarySuffix1=Esta versão do Firebird tornar-se-á a instalação por omissão.
pt.InstallSummarySuffix2=Todavia, preste atenção pois ao instalar esta versão do Firebird
pt.InstallSummarySuffix3=  quando uma versão posterior já está instalada pode causar
pt.InstallSummarySuffix4=                  resultados inesperados.

pt.InstallSummaryCancel1= Se continuar com esta instalação o Firebird será instalado mas não configurado.
pt.InstallSummaryCancel2= Terá que completar a instalação manualmente.
pt.InstallSummaryCancel3= Pretende CANCELAR esta instalação?

pt.InstalledProducts='A análise de reinstalação indica que foram encontradas %s instalações do Firebird ou Interbase.
pt.InstalledProdCountSingular=versão tem
pt.InstalledProdCountPlural=versões têm

pt.FbRunning1=Um Servidor Firebird %s anterior já se encontra em execução.
pt.FbRunning2=     Tem que fechar a aplicação ou parar o serviço
pt.FbRunning3=                 antes de continuar.

pt.PreviousInstallBroken=   (A Instalação aparenta estar danificada por disparidade no texto da versão.)
pt.PreviousInstallGood=   (A Instalação aparenta estar correta.)

pt.IconReadme=Firebird %1 Leia-me
pt.IconUninstall=Remoção do Firebird %1
pt.ReleaseNotes= Notas de Lançamento. (Em inglês, e requer Acrobat Reader.)
pt.InstallationGuide= Guia de Instalação. (Em inglês e requer Acrobat Reader.)
pt.BugFixes= erros corrigidos. (Em inglês e requer Acrobat Reader.)
pt.Uninstall=Remoção do Firebird %1
pt.Winsock2Web1=A biblioteca Winsock 2 não está instalada.
pt.Winsock2Web2=Pretende visitar a página de actualização na Internet do Winsock 2?
pt.NoWinsock2 = Por favor instale a atualização do Winsock 2 antes de continuar
pt.MSWinsock2Update = http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

pt.RunCSNoGuardian=Executar o Servidor Firebird Classic (sem guardian)
pt.RunSSNoGuardian=Executar o Servidor Firebird Superserver (sem guardian)
pt.RunSSWithGuardian=Executar o Servidor Firebird Super (com guardian)
pt.RunCSWithGuardian=Executar o Servidor Firebird Classic (com guardian)
pt.RunISQL=Executar a ferramenta de linha-de-comandos SQL Interactivo

pt.ReadmeFile=leia-me.txt
pt.InstallationReadmeFile=instalação_leia-me.txt

pt.RunCS=Executar o Servidor Firebird Classic
pt.RunSC=Executar o Servidor Firebird SuperClassic
pt.RunSS=Executar o Servidor Firebird Super

