cz.MyAppName=Databázový server Firebird %1
cz.ServerInstall=Plná instalace serveru a vývojových nástrojù.
cz.SuperServerInstall=Plná instalace Super serveru a vývojových nástrojù.
cz.ClassicServerInstall=Plná instalace Classic serveru a vývojových nástrojù.
cz.DeveloperInstall=Instalace klientských nástrojù pro vývojáøe a databázové administrátory.
cz.ClientInstall=Minimální klientská instalace - bez serveru èi nástrojù.
cz.CustomInstall=Uživatelská instalace
cz.SuperServerComponent=Super server binárka
cz.ClassicServerComponent=Classic server binárka
cz.ServerComponent=Serverové souèásti
cz.DevAdminComponent=Nástroje pro vývoj a správu
cz.ClientComponent=Klientské souèásti
cz.UseGuardianTask=Použít &Hlídaèe pro øízení serveru?
cz.UseApplicationTaskMsg=Spouštìt jako &Aplikaci?
cz.TaskGroupDescription=Spouštìt Firebird server jako:
cz.UseServiceTask=Spouštìt jako &Službu?
cz.AutoStartTask=Spustit &Firebird automaticky pøi startu systému?
cz.SuperClassicTask="Použít SuperClassic?"
cz.CopyFbClientToSysTask=Kopírovat &Firebird klientskou knihovnu do složky <system>?
cz.CopyFbClientAsGds32Task=Vytvoøit klientskou knihovnu GDS32.DLL pro podporu &závislých aplikací?
cz.InstallCPLAppletTask="Nainstalovat ovladaè do Ocládacích &Panelù?"
cz.instreg=Aktualizování registrù
cz.instclientCopyFbClient=Kopírování fbclient do složky <sys>
cz.instclientGenGds32=Vytváøení gds32.dll do složky <sys>
cz.instclientDecLibCountGds32="Snížení èítaèe a pøípadné odstranìní sdílené knihovny pro gds32."
cz.instclientDecLibCountFbClient="Snížení èítaèe a pøípadné odstranìní sdílené knihovny pro fbclient."
cz.instsvcSetup=Nastavování služby
cz.instsvcStartQuestion=Spustit službu Firebird nyní?
cz.instsvcStartMsg=Spouštìní služby serveru
cz.instsvcStopMsg="Zastavování služby"
cz.instsvcRemove="Odstraòování služby"
cz.instappStartQuestion=Spustit Firebird nyní?
cz.instappStartMsg=Spouštìní aplikace serveru

cz.InstallSummarySuffix1=Tato verze Firebirdu se stane výchoz instalací.
cz.InstallSummarySuffix2=Pamatujte, že instalování této verze Firebirdu,
cz.InstallSummarySuffix3=   když je již nainstalována verze novìjší,
cz.InstallSummarySuffix4=      mùže mít nepøedvídatelné výsledky.

cz.InstallSummaryCancel1= Pokud budete v této instalaci pokraèovat, Firebird bude nainstalován, ale nebude nastaven.
cz.InstallSummaryCancel2= Instalaci budete muset dokonèit ruènì.
cz.InstallSummaryCancel3= Chcete pøerušit tuto instalaci?

cz.InstalledProducts=Pøedinstalaèní kontrola nalezla existujicí Firebird %s èi Interbase %s.
cz.InstalledProdCountSingular=verze
cz.InstalledProdCountPlural=verzí

cz.FbRunning1=Stávající Firebird %s server je spuštìný.
cz.FbRunning2=  Døíve, než budete pokraèovat, musíte
cz.FbRunning3=       ukonèit program èi službu.

cz.PreviousInstallBroken=   (Z dùvodu chybného oznaèení verze, se instalace zdá být poškozena.)
cz.PreviousInstallGood=   (Instalace se zdá být v poøádku.)

cz.IconReadme=Firebird %1 èti mì
cz.IconUninstall=Odinstalovat Firebird %1
cz.ReleaseNotes= poznámky k vydání. (Vyžaduje Acrobat Reader.)
cz.InstallationGuide= návod k instalaci. (Vyžaduje Acrobat Reader.)
cz.BugFixes= opravené chyby. (Vyžaduje Acrobat Reader.)
cz.Uninstall=Odinstalovat Firebird %1
cz.Winsock2Web1=Není nainstalovaný Winsock 2.
cz.Winsock2Web2=Chcete navštívit domovskou stránku aktualizace Winsock 2?
cz.NoWinsock2=Než budete pokraèovat, nainstalujte prosím aktualizaci Winsock 2.
cz.MSWinsock2Update=http://www.microsoft.com/windows95/downloads/contents/WUAdminTools/S_WUNetworkingTools/W95Sockets2/Default.asp

cz.RunCSNoGuardian=Spustit Firebird Classic server (bez hlídaèe)
cz.RunSSNoGuardian=Spustit Firebird Super server (bez hlídaèe)
cz.RunSSWithGuardian=Spustit Firebird Super server (s hlídaèem)
cz.RunCSWithGuardian=Spustit Firebird Classic server (s hlídaèem)
cz.RunISQL=Spustit interaktivní SQL nástroj založený na pøíkazové øádce

cz.ReadmeFile=ctime.txt
cz.InstallationReadmeFile=instalace_ctime.txt
;cz.IncompleteTranslationNotice=Tento dokument není aktuální. Pro poslední informace, prosím, nahlédnìte do originální anglické dokumentace.
cz.RunCS=Spustit Firebird Classic server
cz.RunSC=Spustit Firebird SuperClassic server
cz.RunSS=Spustit Firebird SuperServer


