LOCAL_PATH := $(call my-dir)

#original path: build_unix/libdb-6.0.la
include $(CLEAR_VARS)

LOCAL_CFLAGS:= -D_GNU_SOURCE -D_REENTRANT -DPIC -ffunction-sections -fdata-sections

LOCAL_C_INCLUDES:= \
	bdb/build_unix\
	bdb/src
LOCAL_SRC_FILES:= \
	src/mutex/mut_pthread.c\
	src/btree/bt_compare.c\
	src/btree/bt_compress.c\
	src/btree/bt_conv.c\
	src/btree/bt_curadj.c\
	src/btree/bt_cursor.c\
	src/btree/bt_delete.c\
	src/btree/bt_method.c\
	src/btree/bt_open.c\
	src/btree/bt_put.c\
	src/btree/bt_rec.c\
	src/btree/bt_reclaim.c\
	src/btree/bt_recno.c\
	src/btree/bt_rsearch.c\
	src/btree/bt_search.c\
	src/btree/bt_split.c\
	src/btree/bt_stat.c\
	src/btree/bt_compact.c\
	src/btree/bt_upgrade.c\
	src/btree/btree_auto.c\
	src/hash/hash.c\
	src/hash/hash_auto.c\
	src/hash/hash_compact.c\
	src/hash/hash_conv.c\
	src/hash/hash_dup.c\
	src/hash/hash_meta.c\
	src/hash/hash_method.c\
	src/hash/hash_open.c\
	src/hash/hash_page.c\
	src/hash/hash_rec.c\
	src/hash/hash_reclaim.c\
	src/hash/hash_stat.c\
	src/hash/hash_upgrade.c\
	src/hash/hash_verify.c\
	src/heap/heap.c\
	src/heap/heap_auto.c\
	src/heap/heap_backup.c\
	src/heap/heap_conv.c\
	src/heap/heap_method.c\
	src/heap/heap_open.c\
	src/heap/heap_rec.c\
	src/heap/heap_reclaim.c\
	src/heap/heap_stat.c\
	src/heap/heap_verify.c\
	src/qam/qam.c\
	src/qam/qam_auto.c\
	src/qam/qam_conv.c\
	src/qam/qam_files.c\
	src/qam/qam_method.c\
	src/qam/qam_open.c\
	src/qam/qam_rec.c\
	src/qam/qam_stat.c\
	src/qam/qam_upgrade.c\
	src/qam/qam_verify.c\
	src/rep/rep_automsg.c\
	src/rep/rep_backup.c\
	src/rep/rep_elect.c\
	src/rep/rep_lease.c\
	src/rep/rep_log.c\
	src/rep/rep_method.c\
	src/rep/rep_record.c\
	src/rep/rep_region.c\
	src/rep/rep_stat.c\
	src/rep/rep_util.c\
	src/rep/rep_verify.c\
	src/os/os_addrinfo.c\
	src/repmgr/repmgr_auto.c\
	src/repmgr/repmgr_automsg.c\
	src/repmgr/repmgr_elect.c\
	src/repmgr/repmgr_method.c\
	src/repmgr/repmgr_msg.c\
	src/repmgr/repmgr_net.c\
	src/repmgr/repmgr_posix.c\
	src/repmgr/repmgr_queue.c\
	src/repmgr/repmgr_rec.c\
	src/repmgr/repmgr_sel.c\
	src/repmgr/repmgr_stat.c\
	src/repmgr/repmgr_util.c\
	src/db/db_ovfl_vrfy.c\
	src/db/db_vrfy.c\
	src/db/db_vrfyutil.c\
	src/btree/bt_verify.c\
	src/log/log_verify.c\
	src/log/log_verify_util.c\
	src/log/log_verify_int.c\
	src/log/log_verify_auto.c\
	src/lock/lock.c\
	src/lock/lock_deadlock.c\
	src/lock/lock_failchk.c\
	src/lock/lock_id.c\
	src/lock/lock_list.c\
	src/lock/lock_method.c\
	src/lock/lock_region.c\
	src/lock/lock_stat.c\
	src/lock/lock_timer.c\
	src/lock/lock_util.c\
	src/mutex/mut_alloc.c\
	src/mutex/mut_failchk.c\
	src/mutex/mut_method.c\
	src/mutex/mut_region.c\
	src/mutex/mut_stat.c\
	lang/dbm/dbm.c\
	lang/hsearch/hsearch.c\
	src/clib/rand.c\
	src/crypto/aes_method.c\
	src/crypto/crypto.c\
	src/crypto/mersenne/mt19937db.c\
	src/crypto/rijndael/rijndael-alg-fst.c\
	src/crypto/rijndael/rijndael-api-fst.c\
	src/blob/blob_fileops.c\
	src/blob/blob_page.c\
	src/blob/blob_stream.c\
	src/blob/blob_util.c\
	src/common/clock.c\
	src/db/crdel_auto.c\
	src/db/crdel_rec.c\
	src/db/db.c\
	src/db/db_am.c\
	src/db/db_auto.c\
	src/db/db_backup.c\
	src/common/db_byteorder.c\
	src/db/db_cam.c\
	src/db/db_cds.c\
	src/db/db_compact.c\
	src/common/db_compint.c\
	src/db/db_conv.c\
	src/db/db_copy.c\
	src/db/db_dispatch.c\
	src/db/db_dup.c\
	src/common/db_err.c\
	src/common/db_getlong.c\
	src/common/db_idspace.c\
	src/db/db_iface.c\
	src/db/db_join.c\
	src/common/db_log2.c\
	src/db/db_meta.c\
	src/db/db_method.c\
	src/db/db_open.c\
	src/db/db_overflow.c\
	src/db/db_pr.c\
	src/db/db_rec.c\
	src/db/db_reclaim.c\
	src/db/db_remove.c\
	src/db/db_rename.c\
	src/db/db_ret.c\
	src/db/db_setid.c\
	src/db/db_setlsn.c\
	src/common/db_shash.c\
	src/db/db_sort_multiple.c\
	src/db/db_stati.c\
	src/db/db_truncate.c\
	src/db/db_upg.c\
	src/db/db_upg_opd.c\
	src/dbreg/dbreg.c\
	src/dbreg/dbreg_stat.c\
	src/dbreg/dbreg_auto.c\
	src/dbreg/dbreg_rec.c\
	src/dbreg/dbreg_util.c\
	src/common/dbt.c\
	src/env/env_alloc.c\
	src/env/env_config.c\
	src/env/env_backup.c\
	src/env/env_failchk.c\
	src/env/env_file.c\
	src/env/env_globals.c\
	src/env/env_open.c\
	src/env/env_method.c\
	src/env/env_name.c\
	src/env/env_recover.c\
	src/env/env_region.c\
	src/env/env_register.c\
	src/env/env_sig.c\
	src/env/env_stat.c\
	src/fileops/fileops_auto.c\
	src/fileops/fop_basic.c\
	src/fileops/fop_rec.c\
	src/fileops/fop_util.c\
	src/hash/hash_func.c\
	src/hmac/hmac.c\
	src/log/log.c\
	src/log/log_archive.c\
	src/log/log_compare.c\
	src/log/log_debug.c\
	src/log/log_get.c\
	src/log/log_method.c\
	src/log/log_print.c\
	src/log/log_put.c\
	src/log/log_stat.c\
	src/common/mkpath.c\
	src/mp/mp_alloc.c\
	src/mp/mp_backup.c\
	src/mp/mp_bh.c\
	src/mp/mp_fget.c\
	src/mp/mp_fmethod.c\
	src/mp/mp_fopen.c\
	src/mp/mp_fput.c\
	src/mp/mp_fset.c\
	src/mp/mp_method.c\
	src/mp/mp_mvcc.c\
	src/mp/mp_region.c\
	src/mp/mp_register.c\
	src/mp/mp_resize.c\
	src/mp/mp_stat.c\
	src/mp/mp_sync.c\
	src/mp/mp_trickle.c\
	src/common/openflags.c\
	src/os/os_abort.c\
	src/os/os_abs.c\
	src/os/os_alloc.c\
	src/os/os_clock.c\
	src/os/os_cpu.c\
	src/os/os_ctime.c\
	src/os/os_config.c\
	src/os/os_dir.c\
	src/os/os_errno.c\
	src/os/os_fid.c\
	src/os/os_flock.c\
	src/os/os_fsync.c\
	src/os/os_getenv.c\
	src/os/os_handle.c\
	src/os/os_map.c\
	src/common/os_method.c\
	src/os/os_mkdir.c\
	src/os/os_open.c\
	src/os/os_path.c\
	src/os/os_pid.c\
	src/os/os_rename.c\
	src/os/os_root.c\
	src/os/os_rpath.c\
	src/os/os_rw.c\
	src/os/os_seek.c\
	src/os/os_stack.c\
	src/os/os_stat.c\
	src/os/os_tmpdir.c\
	src/os/os_truncate.c\
	src/os/os_uid.c\
	src/os/os_unlink.c\
	src/os/os_yield.c\
	src/db/partition.c\
	src/sequence/seq_stat.c\
	src/sequence/sequence.c\
	src/hmac/sha1.c\
	src/clib/snprintf.c\
	src/txn/txn.c\
	src/txn/txn_auto.c\
	src/txn/txn_chkpt.c\
	src/txn/txn_failchk.c\
	src/txn/txn_method.c\
	src/txn/txn_rec.c\
	src/txn/txn_recover.c\
	src/txn/txn_region.c\
	src/txn/txn_stat.c\
	src/txn/txn_util.c\
	src/xa/xa.c\
	src/xa/xa_map.c\
	src/common/zerofill.c
LOCAL_MODULE := libdb-6.0

include $(BUILD_STATIC_LIBRARY)

